"""
Bible book and chapter section titles - multilingual.

Standard nomenclature drawn from historical public-domain Bibles:
- Italian: Diodati 1641 / Riveduta 1924
- English: King James Version 1769 / World English Bible
- Spanish: Reina-Valera 1909
- Portuguese: Almeida 1911
- French: Louis Segond 1910
- German: Luther 1912

These titles are universally known and used across multiple Bible editions.
Chapter section titles are provided ONLY for chapters that have a well-established
traditional title across multiple historical translations.
"""
from typing import Optional

# ==================== 66 BOOK TITLES + DESCRIPTIVE SUBTITLES ====================

BOOK_TITLES = {
    "Genesi": {
        "it": {"title": "Genesi", "subtitle": "Il Libro delle Origini"},
        "en": {"title": "Genesis", "subtitle": "The Book of Beginnings"},
        "es": {"title": "Génesis", "subtitle": "El Libro del Origen"},
        "pt": {"title": "Gênesis", "subtitle": "O Livro das Origens"},
        "fr": {"title": "Genèse", "subtitle": "Le Livre des Origines"},
        "de": {"title": "Genesis", "subtitle": "Das Buch der Anfänge"},
    },
    "Esodo": {
        "it": {"title": "Esodo", "subtitle": "L'Uscita d'Egitto"},
        "en": {"title": "Exodus", "subtitle": "The Going Out of Egypt"},
        "es": {"title": "Éxodo", "subtitle": "La Salida de Egipto"},
        "pt": {"title": "Êxodo", "subtitle": "A Saída do Egito"},
        "fr": {"title": "Exode", "subtitle": "La Sortie d'Égypte"},
        "de": {"title": "Exodus", "subtitle": "Der Auszug aus Ägypten"},
    },
    "Levitico": {
        "it": {"title": "Levitico", "subtitle": "Il Codice Sacerdotale"},
        "en": {"title": "Leviticus", "subtitle": "The Priestly Code"},
        "es": {"title": "Levítico", "subtitle": "El Código Sacerdotal"},
        "pt": {"title": "Levítico", "subtitle": "O Código Sacerdotal"},
        "fr": {"title": "Lévitique", "subtitle": "Le Code Sacerdotal"},
        "de": {"title": "Levitikus", "subtitle": "Das Priesterliche Gesetz"},
    },
    "Numeri": {
        "it": {"title": "Numeri", "subtitle": "Il Cammino nel Deserto"},
        "en": {"title": "Numbers", "subtitle": "The Wilderness Journey"},
        "es": {"title": "Números", "subtitle": "El Camino por el Desierto"},
        "pt": {"title": "Números", "subtitle": "A Jornada pelo Deserto"},
        "fr": {"title": "Nombres", "subtitle": "La Marche au Désert"},
        "de": {"title": "Numeri", "subtitle": "Die Wüstenwanderung"},
    },
    "Deuteronomio": {
        "it": {"title": "Deuteronomio", "subtitle": "La Seconda Legge"},
        "en": {"title": "Deuteronomy", "subtitle": "The Second Law"},
        "es": {"title": "Deuteronomio", "subtitle": "La Segunda Ley"},
        "pt": {"title": "Deuteronômio", "subtitle": "A Segunda Lei"},
        "fr": {"title": "Deutéronome", "subtitle": "La Seconde Loi"},
        "de": {"title": "Deuteronomium", "subtitle": "Das Zweite Gesetz"},
    },
    "Giosuè": {
        "it": {"title": "Giosuè", "subtitle": "La Conquista della Terra Promessa"},
        "en": {"title": "Joshua", "subtitle": "The Conquest of the Promised Land"},
        "es": {"title": "Josué", "subtitle": "La Conquista de la Tierra Prometida"},
        "pt": {"title": "Josué", "subtitle": "A Conquista da Terra Prometida"},
        "fr": {"title": "Josué", "subtitle": "La Conquête de la Terre Promise"},
        "de": {"title": "Josua", "subtitle": "Die Eroberung des Verheißenen Landes"},
    },
    "Giudici": {
        "it": {"title": "Giudici", "subtitle": "I Liberatori d'Israele"},
        "en": {"title": "Judges", "subtitle": "The Deliverers of Israel"},
        "es": {"title": "Jueces", "subtitle": "Los Libertadores de Israel"},
        "pt": {"title": "Juízes", "subtitle": "Os Libertadores de Israel"},
        "fr": {"title": "Juges", "subtitle": "Les Libérateurs d'Israël"},
        "de": {"title": "Richter", "subtitle": "Die Befreier Israels"},
    },
    "Rut": {
        "it": {"title": "Rut", "subtitle": "La Fedeltà nel Dolore"},
        "en": {"title": "Ruth", "subtitle": "Faithfulness in Sorrow"},
        "es": {"title": "Rut", "subtitle": "La Fidelidad en el Dolor"},
        "pt": {"title": "Rute", "subtitle": "A Fidelidade na Dor"},
        "fr": {"title": "Ruth", "subtitle": "La Fidélité dans la Souffrance"},
        "de": {"title": "Rut", "subtitle": "Treue im Leid"},
    },
    "1 Samuele": {
        "it": {"title": "1 Samuele", "subtitle": "Dalla Teocrazia alla Monarchia"},
        "en": {"title": "1 Samuel", "subtitle": "From Theocracy to Monarchy"},
        "es": {"title": "1 Samuel", "subtitle": "De la Teocracia a la Monarquía"},
        "pt": {"title": "1 Samuel", "subtitle": "Da Teocracia à Monarquia"},
        "fr": {"title": "1 Samuel", "subtitle": "De la Théocratie à la Monarchie"},
        "de": {"title": "1. Samuel", "subtitle": "Von der Theokratie zur Monarchie"},
    },
    "2 Samuele": {
        "it": {"title": "2 Samuele", "subtitle": "Il Regno di Davide"},
        "en": {"title": "2 Samuel", "subtitle": "The Reign of David"},
        "es": {"title": "2 Samuel", "subtitle": "El Reinado de David"},
        "pt": {"title": "2 Samuel", "subtitle": "O Reinado de Davi"},
        "fr": {"title": "2 Samuel", "subtitle": "Le Règne de David"},
        "de": {"title": "2. Samuel", "subtitle": "Die Herrschaft Davids"},
    },
    "1 Re": {
        "it": {"title": "1 Re", "subtitle": "Il Regno di Salomone e la Divisione"},
        "en": {"title": "1 Kings", "subtitle": "Solomon's Reign and the Division"},
        "es": {"title": "1 Reyes", "subtitle": "El Reinado de Salomón y la División"},
        "pt": {"title": "1 Reis", "subtitle": "O Reinado de Salomão e a Divisão"},
        "fr": {"title": "1 Rois", "subtitle": "Le Règne de Salomon et la Division"},
        "de": {"title": "1. Könige", "subtitle": "Salomos Herrschaft und die Teilung"},
    },
    "2 Re": {
        "it": {"title": "2 Re", "subtitle": "La Caduta dei Regni"},
        "en": {"title": "2 Kings", "subtitle": "The Fall of the Kingdoms"},
        "es": {"title": "2 Reyes", "subtitle": "La Caída de los Reinos"},
        "pt": {"title": "2 Reis", "subtitle": "A Queda dos Reinos"},
        "fr": {"title": "2 Rois", "subtitle": "La Chute des Royaumes"},
        "de": {"title": "2. Könige", "subtitle": "Der Fall der Königreiche"},
    },
    "1 Cronache": {
        "it": {"title": "1 Cronache", "subtitle": "Le Genealogie e la Storia di Davide"},
        "en": {"title": "1 Chronicles", "subtitle": "The Genealogies and David's History"},
        "es": {"title": "1 Crónicas", "subtitle": "Las Genealogías y la Historia de David"},
        "pt": {"title": "1 Crônicas", "subtitle": "As Genealogias e a História de Davi"},
        "fr": {"title": "1 Chroniques", "subtitle": "Les Généalogies et l'Histoire de David"},
        "de": {"title": "1. Chronik", "subtitle": "Die Genealogien und Davids Geschichte"},
    },
    "2 Cronache": {
        "it": {"title": "2 Cronache", "subtitle": "Storia dei Re di Giuda"},
        "en": {"title": "2 Chronicles", "subtitle": "History of the Kings of Judah"},
        "es": {"title": "2 Crónicas", "subtitle": "Historia de los Reyes de Judá"},
        "pt": {"title": "2 Crônicas", "subtitle": "História dos Reis de Judá"},
        "fr": {"title": "2 Chroniques", "subtitle": "Histoire des Rois de Juda"},
        "de": {"title": "2. Chronik", "subtitle": "Geschichte der Könige Judas"},
    },
    "Esdra": {
        "it": {"title": "Esdra", "subtitle": "Il Ritorno dall'Esilio"},
        "en": {"title": "Ezra", "subtitle": "The Return from Exile"},
        "es": {"title": "Esdras", "subtitle": "El Regreso del Exilio"},
        "pt": {"title": "Esdras", "subtitle": "O Retorno do Exílio"},
        "fr": {"title": "Esdras", "subtitle": "Le Retour de l'Exil"},
        "de": {"title": "Esra", "subtitle": "Die Rückkehr aus dem Exil"},
    },
    "Neemia": {
        "it": {"title": "Neemia", "subtitle": "La Ricostruzione di Gerusalemme"},
        "en": {"title": "Nehemiah", "subtitle": "The Rebuilding of Jerusalem"},
        "es": {"title": "Nehemías", "subtitle": "La Reconstrucción de Jerusalén"},
        "pt": {"title": "Neemias", "subtitle": "A Reconstrução de Jerusalém"},
        "fr": {"title": "Néhémie", "subtitle": "La Reconstruction de Jérusalem"},
        "de": {"title": "Nehemia", "subtitle": "Der Wiederaufbau Jerusalems"},
    },
    "Ester": {
        "it": {"title": "Ester", "subtitle": "La Liberazione del Popolo"},
        "en": {"title": "Esther", "subtitle": "The Deliverance of the People"},
        "es": {"title": "Ester", "subtitle": "La Liberación del Pueblo"},
        "pt": {"title": "Ester", "subtitle": "A Libertação do Povo"},
        "fr": {"title": "Esther", "subtitle": "La Délivrance du Peuple"},
        "de": {"title": "Ester", "subtitle": "Die Befreiung des Volkes"},
    },
    "Giobbe": {
        "it": {"title": "Giobbe", "subtitle": "Il Giusto Sofferente"},
        "en": {"title": "Job", "subtitle": "The Suffering Righteous"},
        "es": {"title": "Job", "subtitle": "El Justo que Sufre"},
        "pt": {"title": "Jó", "subtitle": "O Justo que Sofre"},
        "fr": {"title": "Job", "subtitle": "Le Juste Souffrant"},
        "de": {"title": "Hiob", "subtitle": "Der Leidende Gerechte"},
    },
    "Salmi": {
        "it": {"title": "Salmi", "subtitle": "I Cantici di Israele"},
        "en": {"title": "Psalms", "subtitle": "The Songs of Israel"},
        "es": {"title": "Salmos", "subtitle": "Los Cánticos de Israel"},
        "pt": {"title": "Salmos", "subtitle": "Os Cânticos de Israel"},
        "fr": {"title": "Psaumes", "subtitle": "Les Cantiques d'Israël"},
        "de": {"title": "Psalmen", "subtitle": "Die Lieder Israels"},
    },
    "Proverbi": {
        "it": {"title": "Proverbi", "subtitle": "La Sapienza di Salomone"},
        "en": {"title": "Proverbs", "subtitle": "The Wisdom of Solomon"},
        "es": {"title": "Proverbios", "subtitle": "La Sabiduría de Salomón"},
        "pt": {"title": "Provérbios", "subtitle": "A Sabedoria de Salomão"},
        "fr": {"title": "Proverbes", "subtitle": "La Sagesse de Salomon"},
        "de": {"title": "Sprüche", "subtitle": "Die Weisheit Salomos"},
    },
    "Ecclesiaste": {
        "it": {"title": "Ecclesiaste", "subtitle": "Vanità delle Vanità"},
        "en": {"title": "Ecclesiastes", "subtitle": "Vanity of Vanities"},
        "es": {"title": "Eclesiastés", "subtitle": "Vanidad de Vanidades"},
        "pt": {"title": "Eclesiastes", "subtitle": "Vaidade das Vaidades"},
        "fr": {"title": "Ecclésiaste", "subtitle": "Vanité des Vanités"},
        "de": {"title": "Prediger", "subtitle": "Eitelkeit der Eitelkeiten"},
    },
    "Cantico dei Cantici": {
        "it": {"title": "Cantico dei Cantici", "subtitle": "Il Canto dell'Amore"},
        "en": {"title": "Song of Songs", "subtitle": "The Song of Love"},
        "es": {"title": "Cantar de los Cantares", "subtitle": "El Canto del Amor"},
        "pt": {"title": "Cântico dos Cânticos", "subtitle": "O Cântico do Amor"},
        "fr": {"title": "Cantique des Cantiques", "subtitle": "Le Chant de l'Amour"},
        "de": {"title": "Hohelied", "subtitle": "Das Lied der Liebe"},
    },
    "Isaia": {
        "it": {"title": "Isaia", "subtitle": "Il Profeta Messianico"},
        "en": {"title": "Isaiah", "subtitle": "The Messianic Prophet"},
        "es": {"title": "Isaías", "subtitle": "El Profeta Mesiánico"},
        "pt": {"title": "Isaías", "subtitle": "O Profeta Messiânico"},
        "fr": {"title": "Ésaïe", "subtitle": "Le Prophète Messianique"},
        "de": {"title": "Jesaja", "subtitle": "Der Messianische Prophet"},
    },
    "Geremia": {
        "it": {"title": "Geremia", "subtitle": "Il Profeta del Pianto"},
        "en": {"title": "Jeremiah", "subtitle": "The Weeping Prophet"},
        "es": {"title": "Jeremías", "subtitle": "El Profeta del Llanto"},
        "pt": {"title": "Jeremias", "subtitle": "O Profeta do Choro"},
        "fr": {"title": "Jérémie", "subtitle": "Le Prophète des Larmes"},
        "de": {"title": "Jeremia", "subtitle": "Der Weinende Prophet"},
    },
    "Lamentazioni": {
        "it": {"title": "Lamentazioni", "subtitle": "Il Pianto su Gerusalemme"},
        "en": {"title": "Lamentations", "subtitle": "The Weeping over Jerusalem"},
        "es": {"title": "Lamentaciones", "subtitle": "El Llanto sobre Jerusalén"},
        "pt": {"title": "Lamentações", "subtitle": "O Choro sobre Jerusalém"},
        "fr": {"title": "Lamentations", "subtitle": "Les Pleurs sur Jérusalem"},
        "de": {"title": "Klagelieder", "subtitle": "Die Klage über Jerusalem"},
    },
    "Ezechiele": {
        "it": {"title": "Ezechiele", "subtitle": "Le Visioni della Gloria"},
        "en": {"title": "Ezekiel", "subtitle": "The Visions of Glory"},
        "es": {"title": "Ezequiel", "subtitle": "Las Visiones de la Gloria"},
        "pt": {"title": "Ezequiel", "subtitle": "As Visões da Glória"},
        "fr": {"title": "Ézéchiel", "subtitle": "Les Visions de la Gloire"},
        "de": {"title": "Hesekiel", "subtitle": "Die Visionen der Herrlichkeit"},
    },
    "Daniele": {
        "it": {"title": "Daniele", "subtitle": "Il Profeta dell'Apocalisse"},
        "en": {"title": "Daniel", "subtitle": "The Prophet of the Apocalypse"},
        "es": {"title": "Daniel", "subtitle": "El Profeta del Apocalipsis"},
        "pt": {"title": "Daniel", "subtitle": "O Profeta do Apocalipse"},
        "fr": {"title": "Daniel", "subtitle": "Le Prophète de l'Apocalypse"},
        "de": {"title": "Daniel", "subtitle": "Der Prophet der Apokalypse"},
    },
    "Osea": {
        "it": {"title": "Osea", "subtitle": "L'Amore Fedele di Dio"},
        "en": {"title": "Hosea", "subtitle": "The Faithful Love of God"},
        "es": {"title": "Oseas", "subtitle": "El Amor Fiel de Dios"},
        "pt": {"title": "Oseias", "subtitle": "O Amor Fiel de Deus"},
        "fr": {"title": "Osée", "subtitle": "L'Amour Fidèle de Dieu"},
        "de": {"title": "Hosea", "subtitle": "Die Treue Liebe Gottes"},
    },
    "Gioele": {
        "it": {"title": "Gioele", "subtitle": "Il Giorno del Signore"},
        "en": {"title": "Joel", "subtitle": "The Day of the Lord"},
        "es": {"title": "Joel", "subtitle": "El Día del Señor"},
        "pt": {"title": "Joel", "subtitle": "O Dia do Senhor"},
        "fr": {"title": "Joël", "subtitle": "Le Jour du Seigneur"},
        "de": {"title": "Joel", "subtitle": "Der Tag des Herrn"},
    },
    "Amos": {
        "it": {"title": "Amos", "subtitle": "Il Profeta della Giustizia"},
        "en": {"title": "Amos", "subtitle": "The Prophet of Justice"},
        "es": {"title": "Amós", "subtitle": "El Profeta de la Justicia"},
        "pt": {"title": "Amós", "subtitle": "O Profeta da Justiça"},
        "fr": {"title": "Amos", "subtitle": "Le Prophète de la Justice"},
        "de": {"title": "Amos", "subtitle": "Der Prophet der Gerechtigkeit"},
    },
    "Abdia": {
        "it": {"title": "Abdia", "subtitle": "La Visione su Edom"},
        "en": {"title": "Obadiah", "subtitle": "The Vision Concerning Edom"},
        "es": {"title": "Abdías", "subtitle": "La Visión sobre Edom"},
        "pt": {"title": "Obadias", "subtitle": "A Visão sobre Edom"},
        "fr": {"title": "Abdias", "subtitle": "La Vision sur Édom"},
        "de": {"title": "Obadja", "subtitle": "Die Vision über Edom"},
    },
    "Giona": {
        "it": {"title": "Giona", "subtitle": "Il Profeta Riluttante"},
        "en": {"title": "Jonah", "subtitle": "The Reluctant Prophet"},
        "es": {"title": "Jonás", "subtitle": "El Profeta Renuente"},
        "pt": {"title": "Jonas", "subtitle": "O Profeta Relutante"},
        "fr": {"title": "Jonas", "subtitle": "Le Prophète Réticent"},
        "de": {"title": "Jona", "subtitle": "Der Widerstrebende Prophet"},
    },
    "Michea": {
        "it": {"title": "Michea", "subtitle": "Il Profeta della Speranza"},
        "en": {"title": "Micah", "subtitle": "The Prophet of Hope"},
        "es": {"title": "Miqueas", "subtitle": "El Profeta de la Esperanza"},
        "pt": {"title": "Miqueias", "subtitle": "O Profeta da Esperança"},
        "fr": {"title": "Michée", "subtitle": "Le Prophète de l'Espérance"},
        "de": {"title": "Micha", "subtitle": "Der Prophet der Hoffnung"},
    },
    "Naum": {
        "it": {"title": "Naum", "subtitle": "La Caduta di Ninive"},
        "en": {"title": "Nahum", "subtitle": "The Fall of Nineveh"},
        "es": {"title": "Nahum", "subtitle": "La Caída de Nínive"},
        "pt": {"title": "Naum", "subtitle": "A Queda de Nínive"},
        "fr": {"title": "Nahum", "subtitle": "La Chute de Ninive"},
        "de": {"title": "Nahum", "subtitle": "Der Fall Ninives"},
    },
    "Abacuc": {
        "it": {"title": "Abacuc", "subtitle": "Il Giusto Vivrà per Fede"},
        "en": {"title": "Habakkuk", "subtitle": "The Just Shall Live by Faith"},
        "es": {"title": "Habacuc", "subtitle": "El Justo Vivirá por la Fe"},
        "pt": {"title": "Habacuque", "subtitle": "O Justo Viverá pela Fé"},
        "fr": {"title": "Habacuc", "subtitle": "Le Juste Vivra par la Foi"},
        "de": {"title": "Habakuk", "subtitle": "Der Gerechte Wird aus Glauben Leben"},
    },
    "Sofonia": {
        "it": {"title": "Sofonia", "subtitle": "Il Giorno dell'Ira"},
        "en": {"title": "Zephaniah", "subtitle": "The Day of Wrath"},
        "es": {"title": "Sofonías", "subtitle": "El Día de la Ira"},
        "pt": {"title": "Sofonias", "subtitle": "O Dia da Ira"},
        "fr": {"title": "Sophonie", "subtitle": "Le Jour de la Colère"},
        "de": {"title": "Zefanja", "subtitle": "Der Tag des Zorns"},
    },
    "Aggeo": {
        "it": {"title": "Aggeo", "subtitle": "La Ricostruzione del Tempio"},
        "en": {"title": "Haggai", "subtitle": "The Rebuilding of the Temple"},
        "es": {"title": "Hageo", "subtitle": "La Reconstrucción del Templo"},
        "pt": {"title": "Ageu", "subtitle": "A Reconstrução do Templo"},
        "fr": {"title": "Aggée", "subtitle": "La Reconstruction du Temple"},
        "de": {"title": "Haggai", "subtitle": "Der Wiederaufbau des Tempels"},
    },
    "Zaccaria": {
        "it": {"title": "Zaccaria", "subtitle": "Visioni e Promesse Messianiche"},
        "en": {"title": "Zechariah", "subtitle": "Messianic Visions and Promises"},
        "es": {"title": "Zacarías", "subtitle": "Visiones y Promesas Mesiánicas"},
        "pt": {"title": "Zacarias", "subtitle": "Visões e Promessas Messiânicas"},
        "fr": {"title": "Zacharie", "subtitle": "Visions et Promesses Messianiques"},
        "de": {"title": "Sacharja", "subtitle": "Messianische Visionen und Verheißungen"},
    },
    "Malachia": {
        "it": {"title": "Malachia", "subtitle": "Il Messaggero del Patto"},
        "en": {"title": "Malachi", "subtitle": "The Messenger of the Covenant"},
        "es": {"title": "Malaquías", "subtitle": "El Mensajero del Pacto"},
        "pt": {"title": "Malaquias", "subtitle": "O Mensageiro do Pacto"},
        "fr": {"title": "Malachie", "subtitle": "Le Messager de l'Alliance"},
        "de": {"title": "Maleachi", "subtitle": "Der Bote des Bundes"},
    },
    "Matteo": {
        "it": {"title": "Matteo", "subtitle": "Il Vangelo del Messia Re"},
        "en": {"title": "Matthew", "subtitle": "The Gospel of the King Messiah"},
        "es": {"title": "Mateo", "subtitle": "El Evangelio del Mesías Rey"},
        "pt": {"title": "Mateus", "subtitle": "O Evangelho do Messias Rei"},
        "fr": {"title": "Matthieu", "subtitle": "L'Évangile du Messie Roi"},
        "de": {"title": "Matthäus", "subtitle": "Das Evangelium vom König Messias"},
    },
    "Marco": {
        "it": {"title": "Marco", "subtitle": "Il Vangelo del Servo"},
        "en": {"title": "Mark", "subtitle": "The Gospel of the Servant"},
        "es": {"title": "Marcos", "subtitle": "El Evangelio del Siervo"},
        "pt": {"title": "Marcos", "subtitle": "O Evangelho do Servo"},
        "fr": {"title": "Marc", "subtitle": "L'Évangile du Serviteur"},
        "de": {"title": "Markus", "subtitle": "Das Evangelium des Knechtes"},
    },
    "Luca": {
        "it": {"title": "Luca", "subtitle": "Il Vangelo del Figlio dell'Uomo"},
        "en": {"title": "Luke", "subtitle": "The Gospel of the Son of Man"},
        "es": {"title": "Lucas", "subtitle": "El Evangelio del Hijo del Hombre"},
        "pt": {"title": "Lucas", "subtitle": "O Evangelho do Filho do Homem"},
        "fr": {"title": "Luc", "subtitle": "L'Évangile du Fils de l'Homme"},
        "de": {"title": "Lukas", "subtitle": "Das Evangelium des Menschensohns"},
    },
    "Giovanni": {
        "it": {"title": "Giovanni", "subtitle": "Il Vangelo del Figlio di Dio"},
        "en": {"title": "John", "subtitle": "The Gospel of the Son of God"},
        "es": {"title": "Juan", "subtitle": "El Evangelio del Hijo de Dios"},
        "pt": {"title": "João", "subtitle": "O Evangelho do Filho de Deus"},
        "fr": {"title": "Jean", "subtitle": "L'Évangile du Fils de Dieu"},
        "de": {"title": "Johannes", "subtitle": "Das Evangelium des Sohnes Gottes"},
    },
    "Atti": {
        "it": {"title": "Atti degli Apostoli", "subtitle": "La Nascita della Chiesa"},
        "en": {"title": "Acts", "subtitle": "The Birth of the Church"},
        "es": {"title": "Hechos", "subtitle": "El Nacimiento de la Iglesia"},
        "pt": {"title": "Atos", "subtitle": "O Nascimento da Igreja"},
        "fr": {"title": "Actes", "subtitle": "La Naissance de l'Église"},
        "de": {"title": "Apostelgeschichte", "subtitle": "Die Geburt der Kirche"},
    },
    "Romani": {
        "it": {"title": "Romani", "subtitle": "L'Evangelo della Giustificazione"},
        "en": {"title": "Romans", "subtitle": "The Gospel of Justification"},
        "es": {"title": "Romanos", "subtitle": "El Evangelio de la Justificación"},
        "pt": {"title": "Romanos", "subtitle": "O Evangelho da Justificação"},
        "fr": {"title": "Romains", "subtitle": "L'Évangile de la Justification"},
        "de": {"title": "Römer", "subtitle": "Das Evangelium der Rechtfertigung"},
    },
    "1 Corinzi": {
        "it": {"title": "1 Corinzi", "subtitle": "L'Ordine nella Chiesa"},
        "en": {"title": "1 Corinthians", "subtitle": "Order in the Church"},
        "es": {"title": "1 Corintios", "subtitle": "El Orden en la Iglesia"},
        "pt": {"title": "1 Coríntios", "subtitle": "A Ordem na Igreja"},
        "fr": {"title": "1 Corinthiens", "subtitle": "L'Ordre dans l'Église"},
        "de": {"title": "1. Korinther", "subtitle": "Ordnung in der Gemeinde"},
    },
    "2 Corinzi": {
        "it": {"title": "2 Corinzi", "subtitle": "Il Ministero della Riconciliazione"},
        "en": {"title": "2 Corinthians", "subtitle": "The Ministry of Reconciliation"},
        "es": {"title": "2 Corintios", "subtitle": "El Ministerio de la Reconciliación"},
        "pt": {"title": "2 Coríntios", "subtitle": "O Ministério da Reconciliação"},
        "fr": {"title": "2 Corinthiens", "subtitle": "Le Ministère de la Réconciliation"},
        "de": {"title": "2. Korinther", "subtitle": "Der Dienst der Versöhnung"},
    },
    "Galati": {
        "it": {"title": "Galati", "subtitle": "La Libertà in Cristo"},
        "en": {"title": "Galatians", "subtitle": "Freedom in Christ"},
        "es": {"title": "Gálatas", "subtitle": "La Libertad en Cristo"},
        "pt": {"title": "Gálatas", "subtitle": "A Liberdade em Cristo"},
        "fr": {"title": "Galates", "subtitle": "La Liberté en Christ"},
        "de": {"title": "Galater", "subtitle": "Die Freiheit in Christus"},
    },
    "Efesini": {
        "it": {"title": "Efesini", "subtitle": "L'Unità in Cristo"},
        "en": {"title": "Ephesians", "subtitle": "Unity in Christ"},
        "es": {"title": "Efesios", "subtitle": "La Unidad en Cristo"},
        "pt": {"title": "Efésios", "subtitle": "A Unidade em Cristo"},
        "fr": {"title": "Éphésiens", "subtitle": "L'Unité en Christ"},
        "de": {"title": "Epheser", "subtitle": "Die Einheit in Christus"},
    },
    "Filippesi": {
        "it": {"title": "Filippesi", "subtitle": "La Gioia nel Signore"},
        "en": {"title": "Philippians", "subtitle": "Joy in the Lord"},
        "es": {"title": "Filipenses", "subtitle": "El Gozo en el Señor"},
        "pt": {"title": "Filipenses", "subtitle": "A Alegria no Senhor"},
        "fr": {"title": "Philippiens", "subtitle": "La Joie dans le Seigneur"},
        "de": {"title": "Philipper", "subtitle": "Die Freude im Herrn"},
    },
    "Colossesi": {
        "it": {"title": "Colossesi", "subtitle": "La Supremazia di Cristo"},
        "en": {"title": "Colossians", "subtitle": "The Supremacy of Christ"},
        "es": {"title": "Colosenses", "subtitle": "La Supremacía de Cristo"},
        "pt": {"title": "Colossenses", "subtitle": "A Supremacia de Cristo"},
        "fr": {"title": "Colossiens", "subtitle": "La Suprématie du Christ"},
        "de": {"title": "Kolosser", "subtitle": "Die Überlegenheit Christi"},
    },
    "1 Tessalonicesi": {
        "it": {"title": "1 Tessalonicesi", "subtitle": "L'Attesa del Ritorno di Cristo"},
        "en": {"title": "1 Thessalonians", "subtitle": "Awaiting Christ's Return"},
        "es": {"title": "1 Tesalonicenses", "subtitle": "La Espera del Regreso de Cristo"},
        "pt": {"title": "1 Tessalonicenses", "subtitle": "A Espera do Retorno de Cristo"},
        "fr": {"title": "1 Thessaloniciens", "subtitle": "L'Attente du Retour du Christ"},
        "de": {"title": "1. Thessalonicher", "subtitle": "Das Warten auf die Wiederkunft Christi"},
    },
    "2 Tessalonicesi": {
        "it": {"title": "2 Tessalonicesi", "subtitle": "Il Giorno del Signore"},
        "en": {"title": "2 Thessalonians", "subtitle": "The Day of the Lord"},
        "es": {"title": "2 Tesalonicenses", "subtitle": "El Día del Señor"},
        "pt": {"title": "2 Tessalonicenses", "subtitle": "O Dia do Senhor"},
        "fr": {"title": "2 Thessaloniciens", "subtitle": "Le Jour du Seigneur"},
        "de": {"title": "2. Thessalonicher", "subtitle": "Der Tag des Herrn"},
    },
    "1 Timoteo": {
        "it": {"title": "1 Timoteo", "subtitle": "Il Pastore della Chiesa"},
        "en": {"title": "1 Timothy", "subtitle": "The Pastor of the Church"},
        "es": {"title": "1 Timoteo", "subtitle": "El Pastor de la Iglesia"},
        "pt": {"title": "1 Timóteo", "subtitle": "O Pastor da Igreja"},
        "fr": {"title": "1 Timothée", "subtitle": "Le Pasteur de l'Église"},
        "de": {"title": "1. Timotheus", "subtitle": "Der Hirte der Gemeinde"},
    },
    "2 Timoteo": {
        "it": {"title": "2 Timoteo", "subtitle": "L'Eredità della Fede"},
        "en": {"title": "2 Timothy", "subtitle": "The Heritage of Faith"},
        "es": {"title": "2 Timoteo", "subtitle": "La Herencia de la Fe"},
        "pt": {"title": "2 Timóteo", "subtitle": "A Herança da Fé"},
        "fr": {"title": "2 Timothée", "subtitle": "L'Héritage de la Foi"},
        "de": {"title": "2. Timotheus", "subtitle": "Das Erbe des Glaubens"},
    },
    "Tito": {
        "it": {"title": "Tito", "subtitle": "L'Ordine nella Chiesa di Creta"},
        "en": {"title": "Titus", "subtitle": "Order in the Church of Crete"},
        "es": {"title": "Tito", "subtitle": "El Orden en la Iglesia de Creta"},
        "pt": {"title": "Tito", "subtitle": "A Ordem na Igreja de Creta"},
        "fr": {"title": "Tite", "subtitle": "L'Ordre dans l'Église de Crète"},
        "de": {"title": "Titus", "subtitle": "Ordnung in der Gemeinde von Kreta"},
    },
    "Filemone": {
        "it": {"title": "Filemone", "subtitle": "Il Perdono Cristiano"},
        "en": {"title": "Philemon", "subtitle": "Christian Forgiveness"},
        "es": {"title": "Filemón", "subtitle": "El Perdón Cristiano"},
        "pt": {"title": "Filemom", "subtitle": "O Perdão Cristão"},
        "fr": {"title": "Philémon", "subtitle": "Le Pardon Chrétien"},
        "de": {"title": "Philemon", "subtitle": "Die Christliche Vergebung"},
    },
    "Ebrei": {
        "it": {"title": "Ebrei", "subtitle": "La Superiorità di Cristo"},
        "en": {"title": "Hebrews", "subtitle": "The Superiority of Christ"},
        "es": {"title": "Hebreos", "subtitle": "La Superioridad de Cristo"},
        "pt": {"title": "Hebreus", "subtitle": "A Superioridade de Cristo"},
        "fr": {"title": "Hébreux", "subtitle": "La Supériorité du Christ"},
        "de": {"title": "Hebräer", "subtitle": "Die Überlegenheit Christi"},
    },
    "Giacomo": {
        "it": {"title": "Giacomo", "subtitle": "La Fede Operante"},
        "en": {"title": "James", "subtitle": "Faith in Action"},
        "es": {"title": "Santiago", "subtitle": "La Fe en Acción"},
        "pt": {"title": "Tiago", "subtitle": "A Fé em Ação"},
        "fr": {"title": "Jacques", "subtitle": "La Foi en Action"},
        "de": {"title": "Jakobus", "subtitle": "Der Tätige Glaube"},
    },
    "1 Pietro": {
        "it": {"title": "1 Pietro", "subtitle": "La Speranza nella Sofferenza"},
        "en": {"title": "1 Peter", "subtitle": "Hope in Suffering"},
        "es": {"title": "1 Pedro", "subtitle": "La Esperanza en el Sufrimiento"},
        "pt": {"title": "1 Pedro", "subtitle": "A Esperança no Sofrimento"},
        "fr": {"title": "1 Pierre", "subtitle": "L'Espérance dans la Souffrance"},
        "de": {"title": "1. Petrus", "subtitle": "Hoffnung im Leiden"},
    },
    "2 Pietro": {
        "it": {"title": "2 Pietro", "subtitle": "La Vera Conoscenza"},
        "en": {"title": "2 Peter", "subtitle": "True Knowledge"},
        "es": {"title": "2 Pedro", "subtitle": "El Verdadero Conocimiento"},
        "pt": {"title": "2 Pedro", "subtitle": "O Verdadeiro Conhecimento"},
        "fr": {"title": "2 Pierre", "subtitle": "La Vraie Connaissance"},
        "de": {"title": "2. Petrus", "subtitle": "Die Wahre Erkenntnis"},
    },
    "1 Giovanni": {
        "it": {"title": "1 Giovanni", "subtitle": "L'Amore Fraterno"},
        "en": {"title": "1 John", "subtitle": "Brotherly Love"},
        "es": {"title": "1 Juan", "subtitle": "El Amor Fraternal"},
        "pt": {"title": "1 João", "subtitle": "O Amor Fraternal"},
        "fr": {"title": "1 Jean", "subtitle": "L'Amour Fraternel"},
        "de": {"title": "1. Johannes", "subtitle": "Die Bruderliebe"},
    },
    "2 Giovanni": {
        "it": {"title": "2 Giovanni", "subtitle": "Camminare nella Verità"},
        "en": {"title": "2 John", "subtitle": "Walking in Truth"},
        "es": {"title": "2 Juan", "subtitle": "Andar en la Verdad"},
        "pt": {"title": "2 João", "subtitle": "Andar na Verdade"},
        "fr": {"title": "2 Jean", "subtitle": "Marcher dans la Vérité"},
        "de": {"title": "2. Johannes", "subtitle": "Wandeln in der Wahrheit"},
    },
    "3 Giovanni": {
        "it": {"title": "3 Giovanni", "subtitle": "L'Ospitalità Cristiana"},
        "en": {"title": "3 John", "subtitle": "Christian Hospitality"},
        "es": {"title": "3 Juan", "subtitle": "La Hospitalidad Cristiana"},
        "pt": {"title": "3 João", "subtitle": "A Hospitalidade Cristã"},
        "fr": {"title": "3 Jean", "subtitle": "L'Hospitalité Chrétienne"},
        "de": {"title": "3. Johannes", "subtitle": "Die Christliche Gastfreundschaft"},
    },
    "Giuda": {
        "it": {"title": "Giuda", "subtitle": "Contro i Falsi Maestri"},
        "en": {"title": "Jude", "subtitle": "Against the False Teachers"},
        "es": {"title": "Judas", "subtitle": "Contra los Falsos Maestros"},
        "pt": {"title": "Judas", "subtitle": "Contra os Falsos Mestres"},
        "fr": {"title": "Jude", "subtitle": "Contre les Faux Docteurs"},
        "de": {"title": "Judas", "subtitle": "Gegen die Falschen Lehrer"},
    },
    "Apocalisse": {
        "it": {"title": "Apocalisse", "subtitle": "La Rivelazione di Gesù Cristo"},
        "en": {"title": "Revelation", "subtitle": "The Revelation of Jesus Christ"},
        "es": {"title": "Apocalipsis", "subtitle": "La Revelación de Jesucristo"},
        "pt": {"title": "Apocalipse", "subtitle": "A Revelação de Jesus Cristo"},
        "fr": {"title": "Apocalypse", "subtitle": "La Révélation de Jésus-Christ"},
        "de": {"title": "Offenbarung", "subtitle": "Die Offenbarung Jesu Christi"},
    },
}


# ==================== FAMOUS CHAPTER SECTION TITLES ====================
# Traditional titles found across multiple historical public-domain Bibles.
# Only chapters with widely-recognized standard headings are included.
# Format: (book, chapter) -> {lang: "Title"}

CHAPTER_TITLES = {
    ("Genesi", 1): {
        "it": "La Creazione",
        "en": "The Creation",
        "es": "La Creación",
        "pt": "A Criação",
        "fr": "La Création",
        "de": "Die Schöpfung",
    },
    ("Genesi", 2): {
        "it": "Il Giardino dell'Eden",
        "en": "The Garden of Eden",
        "es": "El Jardín del Edén",
        "pt": "O Jardim do Éden",
        "fr": "Le Jardin d'Éden",
        "de": "Der Garten Eden",
    },
    ("Genesi", 3): {
        "it": "La Caduta dell'Uomo",
        "en": "The Fall of Man",
        "es": "La Caída del Hombre",
        "pt": "A Queda do Homem",
        "fr": "La Chute de l'Homme",
        "de": "Der Sündenfall",
    },
    ("Genesi", 6): {
        "it": "L'Annuncio del Diluvio",
        "en": "The Announcement of the Flood",
        "es": "El Anuncio del Diluvio",
        "pt": "O Anúncio do Dilúvio",
        "fr": "L'Annonce du Déluge",
        "de": "Die Ankündigung der Sintflut",
    },
    ("Genesi", 7): {
        "it": "Il Diluvio",
        "en": "The Flood",
        "es": "El Diluvio",
        "pt": "O Dilúvio",
        "fr": "Le Déluge",
        "de": "Die Sintflut",
    },
    ("Genesi", 11): {
        "it": "La Torre di Babele",
        "en": "The Tower of Babel",
        "es": "La Torre de Babel",
        "pt": "A Torre de Babel",
        "fr": "La Tour de Babel",
        "de": "Der Turmbau zu Babel",
    },
    ("Genesi", 12): {
        "it": "La Chiamata di Abramo",
        "en": "The Call of Abraham",
        "es": "El Llamamiento de Abraham",
        "pt": "O Chamado de Abraão",
        "fr": "La Vocation d'Abraham",
        "de": "Die Berufung Abrahams",
    },
    ("Genesi", 22): {
        "it": "Il Sacrificio di Isacco",
        "en": "The Sacrifice of Isaac",
        "es": "El Sacrificio de Isaac",
        "pt": "O Sacrifício de Isaque",
        "fr": "Le Sacrifice d'Isaac",
        "de": "Die Opferung Isaaks",
    },
    ("Esodo", 3): {
        "it": "Il Roveto Ardente",
        "en": "The Burning Bush",
        "es": "La Zarza Ardiente",
        "pt": "A Sarça Ardente",
        "fr": "Le Buisson Ardent",
        "de": "Der Brennende Dornbusch",
    },
    ("Esodo", 14): {
        "it": "Il Passaggio del Mar Rosso",
        "en": "The Crossing of the Red Sea",
        "es": "El Paso del Mar Rojo",
        "pt": "A Travessia do Mar Vermelho",
        "fr": "Le Passage de la Mer Rouge",
        "de": "Der Durchzug durch das Schilfmeer",
    },
    ("Esodo", 20): {
        "it": "I Dieci Comandamenti",
        "en": "The Ten Commandments",
        "es": "Los Diez Mandamientos",
        "pt": "Os Dez Mandamentos",
        "fr": "Les Dix Commandements",
        "de": "Die Zehn Gebote",
    },
    ("Giosuè", 6): {
        "it": "La Caduta di Gerico",
        "en": "The Fall of Jericho",
        "es": "La Caída de Jericó",
        "pt": "A Queda de Jericó",
        "fr": "La Chute de Jéricho",
        "de": "Der Fall Jerichos",
    },
    ("1 Samuele", 17): {
        "it": "Davide e Golia",
        "en": "David and Goliath",
        "es": "David y Goliat",
        "pt": "Davi e Golias",
        "fr": "David et Goliath",
        "de": "David und Goliat",
    },
    ("1 Re", 3): {
        "it": "La Sapienza di Salomone",
        "en": "The Wisdom of Solomon",
        "es": "La Sabiduría de Salomón",
        "pt": "A Sabedoria de Salomão",
        "fr": "La Sagesse de Salomon",
        "de": "Die Weisheit Salomos",
    },
    ("Salmi", 1): {
        "it": "Le Due Vie",
        "en": "The Two Ways",
        "es": "Los Dos Caminos",
        "pt": "Os Dois Caminhos",
        "fr": "Les Deux Voies",
        "de": "Die Zwei Wege",
    },
    ("Salmi", 22): {
        "it": "Il Salmo del Messia Sofferente",
        "en": "The Psalm of the Suffering Messiah",
        "es": "El Salmo del Mesías que Sufre",
        "pt": "O Salmo do Messias Sofredor",
        "fr": "Le Psaume du Messie Souffrant",
        "de": "Der Psalm des Leidenden Messias",
    },
    ("Salmi", 23): {
        "it": "Il Signore è il Mio Pastore",
        "en": "The Lord is My Shepherd",
        "es": "El Señor es Mi Pastor",
        "pt": "O Senhor é o Meu Pastor",
        "fr": "L'Éternel est Mon Berger",
        "de": "Der Herr ist Mein Hirte",
    },
    ("Salmi", 51): {
        "it": "Il Pentimento di Davide",
        "en": "David's Repentance",
        "es": "El Arrepentimiento de David",
        "pt": "O Arrependimento de Davi",
        "fr": "Le Repentir de David",
        "de": "Davids Buße",
    },
    ("Salmi", 91): {
        "it": "Sotto la Protezione dell'Altissimo",
        "en": "Under the Protection of the Most High",
        "es": "Bajo la Protección del Altísimo",
        "pt": "Sob a Proteção do Altíssimo",
        "fr": "Sous la Protection du Très-Haut",
        "de": "Unter dem Schutz des Höchsten",
    },
    ("Salmi", 119): {
        "it": "L'Eccellenza della Parola di Dio",
        "en": "The Excellence of God's Word",
        "es": "La Excelencia de la Palabra de Dios",
        "pt": "A Excelência da Palavra de Deus",
        "fr": "L'Excellence de la Parole de Dieu",
        "de": "Die Vortrefflichkeit des Wortes Gottes",
    },
    ("Proverbi", 31): {
        "it": "La Donna Virtuosa",
        "en": "The Virtuous Woman",
        "es": "La Mujer Virtuosa",
        "pt": "A Mulher Virtuosa",
        "fr": "La Femme Vertueuse",
        "de": "Die Tugendhafte Frau",
    },
    ("Ecclesiaste", 3): {
        "it": "Un Tempo per Ogni Cosa",
        "en": "A Time for Everything",
        "es": "Tiempo para Todo",
        "pt": "Tempo para Tudo",
        "fr": "Un Temps pour Toute Chose",
        "de": "Ein Jegliches Hat Seine Zeit",
    },
    ("Isaia", 53): {
        "it": "Il Servo Sofferente",
        "en": "The Suffering Servant",
        "es": "El Siervo Sufriente",
        "pt": "O Servo Sofredor",
        "fr": "Le Serviteur Souffrant",
        "de": "Der Leidende Knecht",
    },
    ("Daniele", 3): {
        "it": "I Tre Giovani nella Fornace",
        "en": "The Three Men in the Furnace",
        "es": "Los Tres Jóvenes en el Horno",
        "pt": "Os Três Jovens na Fornalha",
        "fr": "Les Trois Jeunes Gens dans la Fournaise",
        "de": "Die Drei Männer im Feurigen Ofen",
    },
    ("Daniele", 6): {
        "it": "Daniele nella Fossa dei Leoni",
        "en": "Daniel in the Lions' Den",
        "es": "Daniel en el Foso de los Leones",
        "pt": "Daniel na Cova dos Leões",
        "fr": "Daniel dans la Fosse aux Lions",
        "de": "Daniel in der Löwengrube",
    },
    ("Giona", 1): {
        "it": "La Fuga di Giona",
        "en": "Jonah's Flight",
        "es": "La Huida de Jonás",
        "pt": "A Fuga de Jonas",
        "fr": "La Fuite de Jonas",
        "de": "Die Flucht Jonas",
    },
    ("Matteo", 1): {
        "it": "La Genealogia di Gesù",
        "en": "The Genealogy of Jesus",
        "es": "La Genealogía de Jesús",
        "pt": "A Genealogia de Jesus",
        "fr": "La Généalogie de Jésus",
        "de": "Der Stammbaum Jesu",
    },
    ("Matteo", 2): {
        "it": "I Magi e la Fuga in Egitto",
        "en": "The Magi and the Flight to Egypt",
        "es": "Los Magos y la Huida a Egipto",
        "pt": "Os Magos e a Fuga para o Egito",
        "fr": "Les Mages et la Fuite en Égypte",
        "de": "Die Weisen und die Flucht nach Ägypten",
    },
    ("Matteo", 5): {
        "it": "Il Sermone sul Monte - Le Beatitudini",
        "en": "The Sermon on the Mount - The Beatitudes",
        "es": "El Sermón del Monte - Las Bienaventuranzas",
        "pt": "O Sermão da Montanha - As Bem-aventuranças",
        "fr": "Le Sermon sur la Montagne - Les Béatitudes",
        "de": "Die Bergpredigt - Die Seligpreisungen",
    },
    ("Matteo", 6): {
        "it": "Il Padre Nostro",
        "en": "The Lord's Prayer",
        "es": "El Padre Nuestro",
        "pt": "O Pai Nosso",
        "fr": "Le Notre Père",
        "de": "Das Vaterunser",
    },
    ("Matteo", 26): {
        "it": "L'Ultima Cena e il Getsemani",
        "en": "The Last Supper and Gethsemane",
        "es": "La Última Cena y Getsemaní",
        "pt": "A Última Ceia e o Getsêmani",
        "fr": "La Cène et Gethsémané",
        "de": "Das Letzte Abendmahl und Gethsemane",
    },
    ("Matteo", 27): {
        "it": "La Crocifissione",
        "en": "The Crucifixion",
        "es": "La Crucifixión",
        "pt": "A Crucificação",
        "fr": "La Crucifixion",
        "de": "Die Kreuzigung",
    },
    ("Matteo", 28): {
        "it": "La Risurrezione",
        "en": "The Resurrection",
        "es": "La Resurrección",
        "pt": "A Ressurreição",
        "fr": "La Résurrection",
        "de": "Die Auferstehung",
    },
    ("Marco", 16): {
        "it": "La Risurrezione e la Grande Commissione",
        "en": "The Resurrection and the Great Commission",
        "es": "La Resurrección y la Gran Comisión",
        "pt": "A Ressurreição e a Grande Comissão",
        "fr": "La Résurrection et la Grande Mission",
        "de": "Die Auferstehung und der Missionsbefehl",
    },
    ("Luca", 1): {
        "it": "L'Annunciazione",
        "en": "The Annunciation",
        "es": "La Anunciación",
        "pt": "A Anunciação",
        "fr": "L'Annonciation",
        "de": "Die Verkündigung",
    },
    ("Luca", 2): {
        "it": "La Nascita di Gesù",
        "en": "The Birth of Jesus",
        "es": "El Nacimiento de Jesús",
        "pt": "O Nascimento de Jesus",
        "fr": "La Naissance de Jésus",
        "de": "Die Geburt Jesu",
    },
    ("Luca", 15): {
        "it": "Il Figliol Prodigo",
        "en": "The Prodigal Son",
        "es": "El Hijo Pródigo",
        "pt": "O Filho Pródigo",
        "fr": "Le Fils Prodigue",
        "de": "Der Verlorene Sohn",
    },
    ("Luca", 24): {
        "it": "I Discepoli di Emmaus",
        "en": "The Disciples on the Road to Emmaus",
        "es": "Los Discípulos de Emaús",
        "pt": "Os Discípulos de Emaús",
        "fr": "Les Disciples d'Emmaüs",
        "de": "Die Emmaus-Jünger",
    },
    ("Giovanni", 1): {
        "it": "Il Verbo si Fece Carne",
        "en": "The Word Became Flesh",
        "es": "El Verbo se Hizo Carne",
        "pt": "O Verbo se Fez Carne",
        "fr": "La Parole S'est Faite Chair",
        "de": "Das Wort Ward Fleisch",
    },
    ("Giovanni", 3): {
        "it": "Gesù e Nicodemo",
        "en": "Jesus and Nicodemus",
        "es": "Jesús y Nicodemo",
        "pt": "Jesus e Nicodemos",
        "fr": "Jésus et Nicodème",
        "de": "Jesus und Nikodemus",
    },
    ("Giovanni", 4): {
        "it": "La Samaritana al Pozzo",
        "en": "The Samaritan Woman at the Well",
        "es": "La Mujer Samaritana en el Pozo",
        "pt": "A Samaritana no Poço",
        "fr": "La Samaritaine au Puits",
        "de": "Die Samariterin am Brunnen",
    },
    ("Giovanni", 11): {
        "it": "La Risurrezione di Lazzaro",
        "en": "The Raising of Lazarus",
        "es": "La Resurrección de Lázaro",
        "pt": "A Ressurreição de Lázaro",
        "fr": "La Résurrection de Lazare",
        "de": "Die Auferweckung des Lazarus",
    },
    ("Giovanni", 13): {
        "it": "La Lavanda dei Piedi",
        "en": "The Washing of the Feet",
        "es": "El Lavamiento de los Pies",
        "pt": "O Lava-pés",
        "fr": "Le Lavement des Pieds",
        "de": "Die Fußwaschung",
    },
    ("Giovanni", 19): {
        "it": "La Crocifissione di Gesù",
        "en": "The Crucifixion of Jesus",
        "es": "La Crucifixión de Jesús",
        "pt": "A Crucificação de Jesus",
        "fr": "La Crucifixion de Jésus",
        "de": "Die Kreuzigung Jesu",
    },
    ("Giovanni", 20): {
        "it": "La Risurrezione di Gesù",
        "en": "The Resurrection of Jesus",
        "es": "La Resurrección de Jesús",
        "pt": "A Ressurreição de Jesus",
        "fr": "La Résurrection de Jésus",
        "de": "Die Auferstehung Jesu",
    },
    ("Atti", 1): {
        "it": "L'Ascensione di Gesù",
        "en": "The Ascension of Jesus",
        "es": "La Ascensión de Jesús",
        "pt": "A Ascensão de Jesus",
        "fr": "L'Ascension de Jésus",
        "de": "Die Himmelfahrt Jesu",
    },
    ("Atti", 2): {
        "it": "La Pentecoste",
        "en": "Pentecost",
        "es": "Pentecostés",
        "pt": "Pentecostes",
        "fr": "La Pentecôte",
        "de": "Pfingsten",
    },
    ("Atti", 9): {
        "it": "La Conversione di Paolo",
        "en": "The Conversion of Paul",
        "es": "La Conversión de Pablo",
        "pt": "A Conversão de Paulo",
        "fr": "La Conversion de Paul",
        "de": "Die Bekehrung des Paulus",
    },
    ("Romani", 8): {
        "it": "La Vita nello Spirito",
        "en": "Life in the Spirit",
        "es": "La Vida en el Espíritu",
        "pt": "A Vida no Espírito",
        "fr": "La Vie dans l'Esprit",
        "de": "Das Leben im Geist",
    },
    ("Romani", 12): {
        "it": "Il Sacrificio Vivente",
        "en": "The Living Sacrifice",
        "es": "El Sacrificio Vivo",
        "pt": "O Sacrifício Vivo",
        "fr": "Le Sacrifice Vivant",
        "de": "Das Lebendige Opfer",
    },
    ("1 Corinzi", 13): {
        "it": "L'Inno alla Carità",
        "en": "The Hymn to Love",
        "es": "El Himno al Amor",
        "pt": "O Hino ao Amor",
        "fr": "L'Hymne à l'Amour",
        "de": "Das Hohelied der Liebe"
    },
    ("1 Corinzi", 15): {
        "it": "La Risurrezione dei Morti",
        "en": "The Resurrection of the Dead",
        "es": "La Resurrección de los Muertos",
        "pt": "A Ressurreição dos Mortos",
        "fr": "La Résurrection des Morts",
        "de": "Die Auferstehung der Toten",
    },
    ("Galati", 5): {
        "it": "Il Frutto dello Spirito",
        "en": "The Fruit of the Spirit",
        "es": "El Fruto del Espíritu",
        "pt": "O Fruto do Espírito",
        "fr": "Le Fruit de l'Esprit",
        "de": "Die Frucht des Geistes",
    },
    ("Efesini", 6): {
        "it": "L'Armatura di Dio",
        "en": "The Armor of God",
        "es": "La Armadura de Dios",
        "pt": "A Armadura de Deus",
        "fr": "L'Armure de Dieu",
        "de": "Die Waffenrüstung Gottes",
    },
    ("Ebrei", 11): {
        "it": "Gli Eroi della Fede",
        "en": "The Heroes of Faith",
        "es": "Los Héroes de la Fe",
        "pt": "Os Heróis da Fé",
        "fr": "Les Héros de la Foi",
        "de": "Die Helden des Glaubens",
    },
    ("Apocalisse", 1): {
        "it": "La Visione del Cristo Glorificato",
        "en": "The Vision of the Glorified Christ",
        "es": "La Visión del Cristo Glorificado",
        "pt": "A Visão do Cristo Glorificado",
        "fr": "La Vision du Christ Glorifié",
        "de": "Die Vision des Verherrlichten Christus",
    },
    ("Apocalisse", 21): {
        "it": "La Nuova Gerusalemme",
        "en": "The New Jerusalem",
        "es": "La Nueva Jerusalén",
        "pt": "A Nova Jerusalém",
        "fr": "La Nouvelle Jérusalem",
        "de": "Das Neue Jerusalem",
    },
    ("Apocalisse", 22): {
        "it": "Il Ritorno di Cristo",
        "en": "The Return of Christ",
        "es": "El Regreso de Cristo",
        "pt": "O Retorno de Cristo",
        "fr": "Le Retour du Christ",
        "de": "Die Wiederkunft Christi",
    },
}


def _build_reverse_index() -> dict:
    """Build a reverse lookup from translated book name (any language) -> Italian key."""
    index = {}
    for it_key, langs in BOOK_TITLES.items():
        # Always include Italian key (case-insensitive)
        index[it_key.lower()] = it_key
        for lang_data in langs.values():
            translated_title = lang_data.get("title")
            if translated_title:
                index[translated_title.lower()] = it_key
    return index


_BOOK_NAME_REVERSE_INDEX = _build_reverse_index()


def _resolve_italian_key(book_name: str) -> Optional[str]:
    """Map any localized book name back to the canonical Italian key."""
    if not book_name:
        return None
    return _BOOK_NAME_REVERSE_INDEX.get(book_name.lower())


def get_book_info(book_name: str, lang: str = "it") -> Optional[dict]:
    """Get book title and subtitle for a given book in the requested language.

    Accepts the book name in ANY supported language (it/en/es/pt/fr/de) and resolves
    it to the canonical Italian key for lookup.
    """
    italian_key = _resolve_italian_key(book_name)
    if not italian_key:
        return None
    book_info = BOOK_TITLES.get(italian_key)
    if not book_info:
        return None
    return book_info.get(lang) or book_info.get("it")


def get_chapter_title(book_name: str, chapter: int, lang: str = "it") -> Optional[str]:
    """Get the standard chapter section title (None if not a famous chapter).

    Accepts the book name in ANY supported language.
    """
    italian_key = _resolve_italian_key(book_name)
    if not italian_key:
        return None
    chapter_info = CHAPTER_TITLES.get((italian_key, chapter))
    if not chapter_info:
        return None
    return chapter_info.get(lang) or chapter_info.get("it")
