# Bible Data - Nuova Diodati (IT) e Reina Valera 1960 (ES)
# Contenuti biblici reali per l'app Amen!

# ===================== NUOVA DIODATI - ITALIANO =====================

NUOVA_DIODATI = {
    # GENESI
    "Genesi:1": [
        {"verse": 1, "text": "Nel principio Dio creò i cieli e la terra."},
        {"verse": 2, "text": "La terra era informe e vuota e le tenebre coprivano la faccia dell'abisso; e lo Spirito di Dio aleggiava sulla superficie delle acque."},
        {"verse": 3, "text": "Poi Dio disse: «Sia la luce!». E la luce fu."},
        {"verse": 4, "text": "Dio vide che la luce era buona; e Dio separò la luce dalle tenebre."},
        {"verse": 5, "text": "Dio chiamò la luce «giorno» e le tenebre «notte». Così fu sera, poi fu mattina: il primo giorno."},
        {"verse": 6, "text": "Poi Dio disse: «Vi sia un firmamento tra le acque, che separi le acque dalle acque»."},
        {"verse": 7, "text": "Così Dio fece il firmamento e separò le acque che erano sotto il firmamento dalle acque che erano sopra il firmamento. E così fu."},
        {"verse": 8, "text": "Dio chiamò il firmamento «cielo». Così fu sera, poi fu mattina: il secondo giorno."},
        {"verse": 9, "text": "Poi Dio disse: «Le acque che sono sotto il cielo siano raccolte in un unico luogo, e appaia l'asciutto». E così fu."},
        {"verse": 10, "text": "Dio chiamò l'asciutto «terra» e la raccolta delle acque «mari». E Dio vide che questo era buono."},
        {"verse": 11, "text": "Poi Dio disse: «La terra produca germogli, erbe che facciano seme e alberi da frutto che portino sulla terra un frutto contenente il proprio seme, ciascuno secondo la propria specie». E così fu."},
        {"verse": 12, "text": "E la terra produsse germogli, erbe che facevano seme secondo la propria specie e alberi che portavano frutto contenente il proprio seme, ciascuno secondo la propria specie. E Dio vide che questo era buono."},
        {"verse": 13, "text": "Così fu sera, poi fu mattina: il terzo giorno."},
        {"verse": 14, "text": "Poi Dio disse: «Vi siano dei luminari nel firmamento dei cieli per separare il giorno dalla notte; e siano come segni per le stagioni, per i giorni e per gli anni;"},
        {"verse": 15, "text": "e servano come luminari nel firmamento dei cieli per far luce sulla terra». E così fu."},
        {"verse": 16, "text": "Dio fece quindi i due grandi luminari: il luminare maggiore per governare il giorno e il luminare minore per governare la notte; e fece pure le stelle."},
        {"verse": 17, "text": "Dio li mise nel firmamento dei cieli per far luce sulla terra,"},
        {"verse": 18, "text": "per governare il giorno e la notte e per separare la luce dalle tenebre. E Dio vide che questo era buono."},
        {"verse": 19, "text": "Così fu sera, poi fu mattina: il quarto giorno."},
        {"verse": 20, "text": "Poi Dio disse: «Le acque producano in abbondanza esseri viventi, e degli uccelli volino sopra la terra per l'ampia distesa del cielo»."},
        {"verse": 21, "text": "Così Dio creò i grandi animali acquatici e tutti gli esseri viventi che si muovono, di cui le acque producono in abbondanza secondo la loro specie, e ogni volatile secondo la sua specie. E Dio vide che questo era buono."},
        {"verse": 22, "text": "E Dio li benedisse dicendo: «Siate fruttiferi, moltiplicate e riempite le acque dei mari, e gli uccelli si moltiplichino sulla terra»."},
        {"verse": 23, "text": "Così fu sera, poi fu mattina: il quinto giorno."},
        {"verse": 24, "text": "Poi Dio disse: «La terra produca esseri viventi secondo la loro specie: bestiame, rettili e animali selvatici della terra, secondo la loro specie». E così fu."},
        {"verse": 25, "text": "Dio fece gli animali selvatici della terra secondo le loro specie, il bestiame secondo le sue specie e tutti i rettili della terra secondo le loro specie. E Dio vide che questo era buono."},
        {"verse": 26, "text": "Poi Dio disse: «Facciamo l'uomo a nostra immagine e a nostra somiglianza, ed abbia dominio sui pesci del mare, sugli uccelli del cielo, sul bestiame e su tutta la terra, e su tutti i rettili che strisciano sulla terra»."},
        {"verse": 27, "text": "Così Dio creò l'uomo a sua immagine; lo creò a immagine di Dio; li creò maschio e femmina."},
        {"verse": 28, "text": "Dio li benedisse e disse loro: «Siate fruttiferi e moltiplicatevi, riempite la terra e soggiogatela, e dominate sui pesci del mare, sugli uccelli del cielo e sopra ogni essere vivente che si muove sulla terra»."},
        {"verse": 29, "text": "Dio disse: «Ecco, io vi do ogni erba che fa seme sulla superficie di tutta la terra e ogni albero che abbia frutti portatori di seme; questo vi servirà di nutrimento."},
        {"verse": 30, "text": "E a ogni animale della terra, a ogni uccello dei cieli e a tutto ciò che si muove sulla terra ed ha in sé un soffio di vita, io do ogni erba verde per nutrimento». E così fu."},
        {"verse": 31, "text": "Allora Dio vide tutto ciò che aveva fatto, ed ecco, era molto buono. Così fu sera, poi fu mattina: il sesto giorno."},
    ],
    "Genesi:2": [
        {"verse": 1, "text": "Così furono compiuti i cieli e la terra e tutto il loro esercito."},
        {"verse": 2, "text": "Pertanto il settimo giorno Dio terminò l'opera che aveva fatto, e nel settimo giorno si riposò da tutta l'opera che aveva fatto."},
        {"verse": 3, "text": "Dio benedisse il settimo giorno e lo santificò, perché in esso Dio si riposò da tutta l'opera che aveva creato e fatto."},
        {"verse": 4, "text": "Queste sono le origini dei cieli e della terra quando furono creati, nel giorno che l'Eterno Dio fece la terra e i cieli."},
        {"verse": 5, "text": "Non vi era ancora sulla terra alcun arbusto della campagna e nessuna erba della campagna era ancora spuntata, perché l'Eterno Dio non aveva fatto piovere sulla terra e non c'era uomo per coltivare il suolo;"},
        {"verse": 6, "text": "ma un vapore saliva dalla terra e bagnava tutta la superficie del suolo."},
        {"verse": 7, "text": "Allora l'Eterno Dio formò l'uomo dalla polvere della terra, gli soffiò nelle narici un alito di vita, e l'uomo divenne un essere vivente."},
        {"verse": 8, "text": "Or l'Eterno Dio aveva piantato un giardino in Eden, a oriente, e vi pose l'uomo che aveva formato."},
        {"verse": 9, "text": "L'Eterno Dio fece spuntare dal suolo ogni sorta di alberi piacevoli a vedersi e i cui frutti erano buoni da mangiare; in mezzo al giardino vi erano anche l'albero della vita e l'albero della conoscenza del bene e del male."},
        {"verse": 10, "text": "Un fiume usciva da Eden per irrigare il giardino; di là si divideva e diventava quattro corsi d'acqua."},
    ],
    "Genesi:3": [
        {"verse": 1, "text": "Or il serpente era il più astuto di tutte le fiere dei campi che l'Eterno Dio aveva fatto, e disse alla donna: «Dio ha veramente detto: Non mangiate di tutti gli alberi del giardino?»."},
        {"verse": 2, "text": "La donna rispose al serpente: «Del frutto degli alberi del giardino ne possiamo mangiare;"},
        {"verse": 3, "text": "ma del frutto dell'albero che è in mezzo al giardino Dio ha detto: Non ne mangiate e non lo toccate, altrimenti morirete»."},
        {"verse": 4, "text": "Ma il serpente disse alla donna: «Voi non morrete affatto;"},
        {"verse": 5, "text": "ma Dio sa che nel giorno che ne mangerete, i vostri occhi si apriranno e sarete come Dio, conoscendo il bene e il male»."},
        {"verse": 6, "text": "E la donna vide che l'albero era buono per nutrirsi, che era piacevole agli occhi e che l'albero era desiderabile per acquistare conoscenza; prese del suo frutto, ne mangiò e ne diede anche a suo marito che era con lei, ed egli ne mangiò."},
        {"verse": 7, "text": "Allora si aprirono gli occhi di ambedue e si accorsero di essere nudi; e cucirono delle foglie di fico e se ne fecero delle cinture."},
        {"verse": 8, "text": "Poi udirono la voce dell'Eterno Dio che passeggiava nel giardino alla brezza del giorno; e l'uomo e sua moglie si nascosero dalla presenza dell'Eterno Dio fra gli alberi del giardino."},
        {"verse": 9, "text": "Allora l'Eterno Dio chiamò l'uomo e gli disse: «Dove sei?»."},
        {"verse": 10, "text": "Egli rispose: «Ho udito la tua voce nel giardino e ho avuto paura, perché ero nudo, e mi sono nascosto»."},
        {"verse": 11, "text": "Dio disse: «Chi ti ha mostrato che eri nudo? Hai forse mangiato dell'albero del quale ti avevo comandato di non mangiare?»."},
        {"verse": 12, "text": "L'uomo rispose: «La donna che tu mi hai messo accanto, è lei che mi ha dato dell'albero, e io ne ho mangiato»."},
        {"verse": 13, "text": "E l'Eterno Dio disse alla donna: «Perché hai fatto questo?». La donna rispose: «Il serpente mi ha ingannata, e io ne ho mangiato»."},
        {"verse": 14, "text": "Allora l'Eterno Dio disse al serpente: «Poiché hai fatto questo, sii maledetto fra tutto il bestiame e fra tutti gli animali dei campi! Tu camminerai sul tuo ventre e mangerai polvere tutti i giorni della tua vita."},
        {"verse": 15, "text": "E io porrò inimicizia fra te e la donna e fra la tua discendenza e la discendenza di lei; questa ti schiaccerà il capo e tu le ferirai il calcagno»."},
    ],
    # SALMI
    "Salmi:1": [
        {"verse": 1, "text": "Beato l'uomo che non cammina nel consiglio degli empi, non si ferma nella via dei peccatori e non si siede in compagnia degli schernitori,"},
        {"verse": 2, "text": "ma il cui diletto è nella legge dell'Eterno e sulla sua legge medita giorno e notte."},
        {"verse": 3, "text": "Egli sarà come un albero piantato lungo corsi d'acqua, che dà il suo frutto nella sua stagione e le sue foglie non appassiscono; e tutto quello che fa prospererà."},
        {"verse": 4, "text": "Non così gli empi, poiché essi sono come la pula che il vento spazza via."},
        {"verse": 5, "text": "Perciò gli empi non reggeranno nel giudizio, né i peccatori nell'assemblea dei giusti."},
        {"verse": 6, "text": "Poiché l'Eterno conosce la via dei giusti, ma la via degli empi porta alla rovina."},
    ],
    "Salmi:23": [
        {"verse": 1, "text": "L'Eterno è il mio pastore, nulla mi mancherà."},
        {"verse": 2, "text": "Egli mi fa riposare in verdeggianti pascoli, mi guida lungo le acque tranquille."},
        {"verse": 3, "text": "Egli ristora la mia anima, mi guida per sentieri di giustizia per amore del suo nome."},
        {"verse": 4, "text": "Anche se camminassi nella valle dell'ombra della morte, non temerei alcun male, perché tu sei con me; il tuo bastone e la tua verga sono quelli che mi consolano."},
        {"verse": 5, "text": "Tu prepari davanti a me una mensa in presenza dei miei nemici; tu ungi il mio capo con olio; la mia coppa trabocca."},
        {"verse": 6, "text": "Certo, beni e benignità mi accompagneranno tutti i giorni della mia vita; e io abiterò nella casa dell'Eterno per lunghi giorni."},
    ],
    "Salmi:91": [
        {"verse": 1, "text": "Chi dimora nel riparo dell'Altissimo, riposa all'ombra dell'Onnipotente."},
        {"verse": 2, "text": "Io dico dell'Eterno: «Egli è il mio rifugio e la mia fortezza, il mio Dio in cui confido»."},
        {"verse": 3, "text": "Certo egli ti libererà dal laccio del cacciatore e dalla peste mortifera."},
        {"verse": 4, "text": "Egli ti coprirà con le sue penne e sotto le sue ali troverai rifugio; la sua verità ti sarà scudo e corazza."},
        {"verse": 5, "text": "Tu non temerai lo spavento notturno, né la freccia che vola di giorno,"},
        {"verse": 6, "text": "né la peste che vaga nelle tenebre, né la calamità che devasta a mezzogiorno."},
        {"verse": 7, "text": "Mille cadranno al tuo fianco e diecimila alla tua destra, ma nulla ti raggiungerà."},
        {"verse": 8, "text": "Certamente tu osserverai con i tuoi occhi e vedrai la retribuzione degli empi."},
        {"verse": 9, "text": "Poiché tu hai detto: «L'Eterno è il mio rifugio»; tu hai fatto dell'Altissimo il tuo riparo,"},
        {"verse": 10, "text": "nessun male ti coglierà e nessun flagello si accosterà alla tua tenda."},
        {"verse": 11, "text": "Poiché egli comanderà ai suoi angeli di custodirti in tutte le tue vie."},
        {"verse": 12, "text": "Essi ti porteranno sulle loro mani, perché il tuo piede non inciampi in alcuna pietra."},
        {"verse": 13, "text": "Tu calpesterai il leone e la vipera, schiaccerai il leoncello e il serpente."},
        {"verse": 14, "text": "«Poiché egli ha riposto in me il suo amore, io lo libererò e lo metterò al sicuro, perché conosce il mio nome."},
        {"verse": 15, "text": "Egli mi invocherà e io gli risponderò; sarò con lui nella sventura; lo libererò e lo glorificherò."},
        {"verse": 16, "text": "Lo sazierò di lunga vita e gli farò vedere la mia salvezza»."},
    ],
    "Salmi:119": [
        {"verse": 1, "text": "Beati quelli che sono integri nelle loro vie e camminano nella legge dell'Eterno."},
        {"verse": 2, "text": "Beati quelli che osservano le sue testimonianze e lo cercano con tutto il cuore,"},
        {"verse": 3, "text": "che non commettono alcuna iniquità e camminano nelle sue vie."},
        {"verse": 4, "text": "Tu hai ordinato i tuoi precetti perché siano osservati diligentemente."},
        {"verse": 5, "text": "Oh, fossero le mie vie dirette all'osservanza dei tuoi statuti!"},
        {"verse": 6, "text": "Allora non sarei confuso, quando considero tutti i tuoi comandamenti."},
        {"verse": 7, "text": "Ti celebrerò con cuore retto, quando avrò imparato i tuoi giusti giudizi."},
        {"verse": 8, "text": "Osserverò i tuoi statuti; non abbandonarmi mai."},
        {"verse": 105, "text": "La tua parola è una lampada al mio piede e una luce sul mio sentiero."},
    ],
    # PROVERBI
    "Proverbi:1": [
        {"verse": 1, "text": "Proverbi di Salomone, figlio di Davide, re d'Israele,"},
        {"verse": 2, "text": "per conoscere la sapienza e l'ammaestramento, per comprendere i detti profondi,"},
        {"verse": 3, "text": "per ricevere un ammaestramento di buon senso, giustizia, giudizio ed equità,"},
        {"verse": 4, "text": "per dare accortezza ai semplici e conoscenza e riflessione al giovane."},
        {"verse": 5, "text": "Il saggio ascolti e accrescerà il suo sapere, e l'uomo intelligente ne trarrà saggi consigli,"},
        {"verse": 6, "text": "per comprendere i proverbi e le allegorie, le parole dei saggi e i loro enigmi."},
        {"verse": 7, "text": "Il timore dell'Eterno è il principio della conoscenza; gli stolti disprezzano la sapienza e l'ammaestramento."},
    ],
    "Proverbi:3": [
        {"verse": 1, "text": "Figlio mio, non dimenticare il mio insegnamento e il tuo cuore custodisca i miei comandamenti,"},
        {"verse": 2, "text": "perché ti procureranno lunghi giorni, anni di vita e di pace."},
        {"verse": 3, "text": "Bontà e verità non ti abbandonino; legale al tuo collo, scrivile sulla tavola del tuo cuore;"},
        {"verse": 4, "text": "così troverai grazia e buon senno agli occhi di Dio e degli uomini."},
        {"verse": 5, "text": "Confida nell'Eterno con tutto il tuo cuore e non appoggiarti sul tuo intendimento;"},
        {"verse": 6, "text": "riconoscilo in tutte le tue vie, ed egli raddrizzerà i tuoi sentieri."},
        {"verse": 7, "text": "Non ritenerti saggio ai tuoi occhi; temi l'Eterno e allontanati dal male;"},
        {"verse": 8, "text": "questo sarà salute al tuo corpo e un refrigerio alle tue ossa."},
    ],
    # MATTEO
    "Matteo:5": [
        {"verse": 1, "text": "Vedendo le folle, Gesù salì sul monte e, come si fu seduto, i suoi discepoli gli si accostarono."},
        {"verse": 2, "text": "Allora egli prese a insegnare loro, dicendo:"},
        {"verse": 3, "text": "«Beati i poveri in spirito, perché di loro è il regno dei cieli."},
        {"verse": 4, "text": "Beati coloro che fanno cordoglio, perché saranno consolati."},
        {"verse": 5, "text": "Beati i mansueti, perché erediteranno la terra."},
        {"verse": 6, "text": "Beati coloro che sono affamati e assetati di giustizia, perché saranno saziati."},
        {"verse": 7, "text": "Beati i misericordiosi, perché otterranno misericordia."},
        {"verse": 8, "text": "Beati i puri di cuore, perché vedranno Dio."},
        {"verse": 9, "text": "Beati coloro che si adoperano per la pace, perché saranno chiamati figli di Dio."},
        {"verse": 10, "text": "Beati coloro che sono perseguitati a causa della giustizia, perché di loro è il regno dei cieli."},
        {"verse": 11, "text": "Beati sarete voi, quando vi insulteranno e vi perseguiteranno e, mentendo, diranno contro di voi ogni sorta di male per causa mia."},
        {"verse": 12, "text": "Rallegratevi e giubilate, perché il vostro premio è grande nei cieli; poiché così hanno perseguitato i profeti che furono prima di voi."},
        {"verse": 13, "text": "Voi siete il sale della terra; ma se il sale diventa insipido, con che cosa gli si renderà il sapore? A null'altro serve che ad essere gettato via e ad essere calpestato dagli uomini."},
        {"verse": 14, "text": "Voi siete la luce del mondo; una città posta sopra un monte non può essere nascosta."},
        {"verse": 15, "text": "Similmente non si accende una lampada per metterla sotto il moggio, ma sul candeliere; e così fa luce a tutti coloro che sono in casa."},
        {"verse": 16, "text": "Così risplenda la vostra luce davanti agli uomini, affinché vedano le vostre buone opere e glorifichino il Padre vostro che è nei cieli."},
    ],
    "Matteo:6": [
        {"verse": 9, "text": "Voi dunque pregate così: Padre nostro che sei nei cieli, sia santificato il tuo nome."},
        {"verse": 10, "text": "Venga il tuo regno. Sia fatta la tua volontà in terra come in cielo."},
        {"verse": 11, "text": "Dacci oggi il nostro pane quotidiano."},
        {"verse": 12, "text": "E rimettici i nostri debiti, come anche noi li rimettiamo ai nostri debitori."},
        {"verse": 13, "text": "E non indurci in tentazione, ma liberaci dal male. Perché tuo è il regno, la potenza e la gloria in eterno. Amen."},
        {"verse": 25, "text": "Perciò vi dico: Non siate con ansietà solleciti per la vostra vita, di quel che mangerete o di quel che berrete; né per il vostro corpo, di che vi vestirete. Non è la vita più del nutrimento e il corpo più del vestito?"},
        {"verse": 26, "text": "Guardate gli uccelli del cielo: non seminano, non mietono e non raccolgono in granai; eppure il Padre vostro celeste li nutre. Non valete voi molto più di loro?"},
        {"verse": 33, "text": "Ma cercate prima il regno di Dio e la sua giustizia, e tutte queste cose vi saranno date in più."},
        {"verse": 34, "text": "Non siate dunque in ansietà del domani, perché il domani si prenderà cura per conto suo. Basta a ciascun giorno il suo affanno."},
    ],
    # GIOVANNI
    "Giovanni:1": [
        {"verse": 1, "text": "Nel principio era la Parola e la Parola era presso Dio, e la Parola era Dio."},
        {"verse": 2, "text": "Egli era nel principio con Dio."},
        {"verse": 3, "text": "Tutte le cose sono state fatte per mezzo di lui, e senza di lui nessuna delle cose fatte è stata fatta."},
        {"verse": 4, "text": "In lui era la vita, e la vita era la luce degli uomini."},
        {"verse": 5, "text": "E la luce risplende nelle tenebre, e le tenebre non l'hanno compresa."},
        {"verse": 6, "text": "Vi fu un uomo mandato da Dio, il cui nome era Giovanni."},
        {"verse": 7, "text": "Egli venne come testimone per rendere testimonianza alla luce, affinché tutti credessero per mezzo di lui."},
        {"verse": 8, "text": "Egli non era la luce, ma fu mandato per rendere testimonianza alla luce."},
        {"verse": 9, "text": "Egli era la vera luce, che illumina ogni uomo che viene nel mondo."},
        {"verse": 10, "text": "Egli era nel mondo, e il mondo fu fatto per mezzo di lui, ma il mondo non lo ha conosciuto."},
        {"verse": 11, "text": "Egli è venuto in casa sua, e i suoi non lo hanno ricevuto."},
        {"verse": 12, "text": "Ma a tutti coloro che lo hanno ricevuto, egli ha dato l'autorità di diventare figli di Dio, a quelli cioè che credono nel suo nome,"},
        {"verse": 13, "text": "i quali non sono nati da sangue, né da volontà di carne, né da volontà di uomo, ma sono nati da Dio."},
        {"verse": 14, "text": "E la Parola si è fatta carne ed ha abitato fra di noi; e noi abbiamo contemplato la sua gloria, gloria come dell'unigenito proceduto dal Padre, piena di grazia e di verità."},
    ],
    "Giovanni:3": [
        {"verse": 1, "text": "Or c'era tra i farisei un uomo di nome Nicodemo, uno dei capi dei Giudei."},
        {"verse": 2, "text": "Questi venne a Gesù di notte e gli disse: «Rabbì, noi sappiamo che tu sei un dottore venuto da Dio, perché nessuno può fare i miracoli che tu fai, se Dio non è con lui»."},
        {"verse": 3, "text": "Gesù gli rispose e disse: «In verità, in verità ti dico che se uno non è nato di nuovo, non può vedere il regno di Dio»."},
        {"verse": 4, "text": "Nicodemo gli disse: «Come può un uomo nascere quando è vecchio? Può egli entrare una seconda volta nel grembo di sua madre e nascere?»."},
        {"verse": 5, "text": "Gesù rispose: «In verità, in verità ti dico che se uno non è nato d'acqua e di Spirito, non può entrare nel regno di Dio."},
        {"verse": 6, "text": "Ciò che è nato dalla carne è carne, e ciò che è nato dallo Spirito è spirito."},
        {"verse": 7, "text": "Non meravigliarti se ti ho detto: Dovete nascere di nuovo."},
        {"verse": 8, "text": "Il vento soffia dove vuole e tu ne odi il suono, ma non sai da dove viene né dove va; così è per chiunque è nato dallo Spirito»."},
        {"verse": 14, "text": "E come Mosè innalzò il serpente nel deserto, così bisogna che il Figlio dell'uomo sia innalzato,"},
        {"verse": 15, "text": "affinché chiunque crede in lui non perisca, ma abbia vita eterna."},
        {"verse": 16, "text": "Poiché Dio ha tanto amato il mondo, che ha dato il suo unigenito Figlio, affinché chiunque crede in lui non perisca, ma abbia vita eterna."},
        {"verse": 17, "text": "Dio infatti non ha mandato il proprio Figlio nel mondo per condannare il mondo, ma affinché il mondo sia salvato per mezzo di lui."},
        {"verse": 18, "text": "Chi crede in lui non è condannato, ma chi non crede è già condannato, perché non ha creduto nel nome dell'unigenito Figlio di Dio."},
    ],
    "Giovanni:14": [
        {"verse": 1, "text": "Il vostro cuore non sia turbato; credete in Dio e credete anche in me."},
        {"verse": 2, "text": "Nella casa del Padre mio ci sono molte dimore; se no, ve lo avrei detto; io vado a prepararvi un luogo."},
        {"verse": 3, "text": "E quando sarò andato e vi avrò preparato un luogo, tornerò e vi accoglierò presso di me, affinché dove sono io siate anche voi."},
        {"verse": 4, "text": "E voi sapete dove io vado e sapete anche la via»."},
        {"verse": 5, "text": "Tommaso gli disse: «Signore, non sappiamo dove vai; come possiamo sapere la via?»."},
        {"verse": 6, "text": "Gesù gli disse: «Io sono la via, la verità e la vita; nessuno viene al Padre se non per mezzo di me."},
        {"verse": 7, "text": "Se mi aveste conosciuto, avreste conosciuto anche il Padre mio; e fin da ora lo conoscete e lo avete visto»."},
        {"verse": 15, "text": "Se mi amate, osservate i miei comandamenti."},
        {"verse": 16, "text": "Ed io pregherò il Padre, e vi darà un altro Consolatore, che rimanga con voi per sempre,"},
        {"verse": 17, "text": "lo Spirito della verità, che il mondo non può ricevere, perché non lo vede e non lo conosce; ma voi lo conoscete, perché dimora con voi e sarà in voi."},
        {"verse": 26, "text": "Ma il Consolatore, lo Spirito Santo, che il Padre manderà nel mio nome, vi insegnerà ogni cosa e vi ricorderà tutto quello che vi ho detto."},
        {"verse": 27, "text": "Vi lascio la pace, vi do la mia pace. Io ve la do non come la dà il mondo; il vostro cuore non sia turbato e non si spaventi."},
    ],
    # ROMANI
    "Romani:8": [
        {"verse": 1, "text": "Ora dunque non vi è alcuna condanna per coloro che sono in Cristo Gesù, i quali non camminano secondo la carne ma secondo lo Spirito,"},
        {"verse": 2, "text": "perché la legge dello Spirito della vita in Cristo Gesù mi ha liberato dalla legge del peccato e della morte."},
        {"verse": 14, "text": "Poiché tutti quelli che sono condotti dallo Spirito di Dio sono figli di Dio."},
        {"verse": 15, "text": "Voi infatti non avete ricevuto uno spirito di schiavitù per cadere nuovamente nella paura, ma avete ricevuto lo Spirito di adozione per il quale gridiamo: «Abbà, Padre»."},
        {"verse": 16, "text": "Lo Spirito stesso rende testimonianza al nostro spirito che noi siamo figli di Dio."},
        {"verse": 17, "text": "Or se siamo figli, siamo anche eredi; eredi di Dio e coeredi di Cristo, se pure soffriamo con lui per essere anche con lui glorificati."},
        {"verse": 28, "text": "Or noi sappiamo che tutte le cose cooperano al bene di quelli che amano Dio, i quali sono chiamati secondo il suo proponimento."},
        {"verse": 31, "text": "Che diremo dunque di queste cose? Se Dio è per noi, chi sarà contro di noi?"},
        {"verse": 32, "text": "Colui che non ha risparmiato il suo proprio Figlio, ma lo ha dato per tutti noi, come non ci donerà anche tutte le cose con lui?"},
        {"verse": 35, "text": "Chi ci separerà dall'amore di Cristo? Sarà l'afflizione, o la distretta, o la persecuzione, o la fame, o la nudità, o il pericolo, o la spada?"},
        {"verse": 37, "text": "Ma in tutte queste cose noi siamo più che vincitori per mezzo di colui che ci ha amati."},
        {"verse": 38, "text": "Infatti io sono persuaso che né morte né vita, né angeli né principati, né cose presenti né cose future, né potenze,"},
        {"verse": 39, "text": "né altezza né profondità, né alcun'altra creatura potrà separarci dall'amore di Dio che è in Cristo Gesù, nostro Signore."},
    ],
    # FILIPPESI
    "Filippesi:4": [
        {"verse": 4, "text": "Rallegratevi sempre nel Signore; ve lo ripeto, rallegratevi."},
        {"verse": 5, "text": "La vostra mansuetudine sia nota a tutti gli uomini. Il Signore è vicino."},
        {"verse": 6, "text": "Non angustiatevi di nulla, ma in ogni cosa fate conoscere le vostre richieste a Dio mediante preghiera e supplica, con ringraziamento."},
        {"verse": 7, "text": "E la pace di Dio, che supera ogni intelligenza, custodirà i vostri cuori e le vostre menti in Cristo Gesù."},
        {"verse": 8, "text": "Del resto, fratelli, tutte le cose che sono vere, tutte le cose che sono onorevoli, tutte le cose che sono giuste, tutte le cose che sono pure, tutte le cose che sono amabili, tutte le cose che sono di buona fama, se vi è qualche virtù e se vi è qualche lode, pensate a queste cose."},
        {"verse": 11, "text": "Non lo dico perché mi trovi nel bisogno, poiché io ho imparato ad essere contento nello stato in cui mi trovo."},
        {"verse": 12, "text": "So vivere in povertà e so anche vivere nell'abbondanza; in ogni maniera e in ogni cosa ho imparato a saziarmi e ad aver fame, ad abbondare e a soffrire la penuria."},
        {"verse": 13, "text": "Io posso ogni cosa in Cristo che mi fortifica."},
        {"verse": 19, "text": "E il mio Dio supplirà a ogni vostro bisogno secondo le sue ricchezze in gloria, in Cristo Gesù."},
    ],
    # APOCALISSE
    "Apocalisse:1": [
        {"verse": 1, "text": "La rivelazione di Gesù Cristo, che Dio gli ha data per mostrare ai suoi servi le cose che devono accadere rapidamente e che egli ha fatto conoscere, mandandola per mezzo del suo angelo al suo servo Giovanni,"},
        {"verse": 2, "text": "il quale ha attestato come parola di Dio e come testimonianza di Gesù Cristo tutto ciò che ha visto."},
        {"verse": 3, "text": "Beato chi legge e beati coloro che ascoltano le parole di questa profezia e custodiscono le cose che vi sono scritte, perché il tempo è vicino."},
        {"verse": 8, "text": "«Io sono l'Alfa e l'Omega, il principio e la fine», dice il Signore «che è, che era e che ha da venire, l'Onnipotente»."},
    ],
    "Apocalisse:21": [
        {"verse": 1, "text": "Poi vidi un nuovo cielo e una nuova terra, perché il primo cielo e la prima terra erano passati, e il mare non c'era più."},
        {"verse": 2, "text": "E io, Giovanni, vidi la santa città, la nuova Gerusalemme, che scendeva dal cielo da presso Dio, preparata come una sposa adorna per il suo sposo."},
        {"verse": 3, "text": "E udii una grande voce dal cielo che diceva: «Ecco il tabernacolo di Dio con gli uomini! Ed egli abiterà con loro; e essi saranno suo popolo e Dio stesso sarà con loro e sarà il loro Dio."},
        {"verse": 4, "text": "E Dio asciugherà ogni lacrima dai loro occhi, e non ci sarà più la morte né cordoglio né grido né fatica, perché le cose di prima sono passate»."},
        {"verse": 5, "text": "E colui che sedeva sul trono disse: «Ecco, io faccio tutte le cose nuove». Poi mi disse: «Scrivi, perché queste parole sono veraci e fedeli»."},
    ],
}

# ===================== REINA VALERA 1960 - ESPAÑOL =====================

REINA_VALERA_1960 = {
    # GÉNESIS
    "Génesis:1": [
        {"verse": 1, "text": "En el principio creó Dios los cielos y la tierra."},
        {"verse": 2, "text": "Y la tierra estaba desordenada y vacía, y las tinieblas estaban sobre la faz del abismo, y el Espíritu de Dios se movía sobre la faz de las aguas."},
        {"verse": 3, "text": "Y dijo Dios: Sea la luz; y fue la luz."},
        {"verse": 4, "text": "Y vio Dios que la luz era buena; y separó Dios la luz de las tinieblas."},
        {"verse": 5, "text": "Y llamó Dios a la luz Día, y a las tinieblas llamó Noche. Y fue la tarde y la mañana un día."},
        {"verse": 6, "text": "Luego dijo Dios: Haya expansión en medio de las aguas, y separe las aguas de las aguas."},
        {"verse": 7, "text": "E hizo Dios la expansión, y separó las aguas que estaban debajo de la expansión, de las aguas que estaban sobre la expansión. Y fue así."},
        {"verse": 8, "text": "Y llamó Dios a la expansión Cielos. Y fue la tarde y la mañana el día segundo."},
        {"verse": 9, "text": "Dijo también Dios: Júntense las aguas que están debajo de los cielos en un lugar, y descúbrase lo seco. Y fue así."},
        {"verse": 10, "text": "Y llamó Dios a lo seco Tierra, y a la reunión de las aguas llamó Mares. Y vio Dios que era bueno."},
        {"verse": 11, "text": "Después dijo Dios: Produzca la tierra hierba verde, hierba que dé semilla; árbol de fruto que dé fruto según su género, que su semilla esté en él, sobre la tierra. Y fue así."},
        {"verse": 26, "text": "Entonces dijo Dios: Hagamos al hombre a nuestra imagen, conforme a nuestra semejanza; y señoree en los peces del mar, en las aves de los cielos, en las bestias, en toda la tierra, y en todo animal que se arrastra sobre la tierra."},
        {"verse": 27, "text": "Y creó Dios al hombre a su imagen, a imagen de Dios lo creó; varón y hembra los creó."},
        {"verse": 28, "text": "Y los bendijo Dios, y les dijo: Fructificad y multiplicaos; llenad la tierra, y sojuzgadla, y señoread en los peces del mar, en las aves de los cielos, y en todas las bestias que se mueven sobre la tierra."},
        {"verse": 31, "text": "Y vio Dios todo lo que había hecho, y he aquí que era bueno en gran manera. Y fue la tarde y la mañana el día sexto."},
    ],
    # SALMOS
    "Salmos:23": [
        {"verse": 1, "text": "Jehová es mi pastor; nada me faltará."},
        {"verse": 2, "text": "En lugares de delicados pastos me hará descansar; junto a aguas de reposo me pastoreará."},
        {"verse": 3, "text": "Confortará mi alma; me guiará por sendas de justicia por amor de su nombre."},
        {"verse": 4, "text": "Aunque ande en valle de sombra de muerte, no temeré mal alguno, porque tú estarás conmigo; tu vara y tu cayado me infundirán aliento."},
        {"verse": 5, "text": "Aderezas mesa delante de mí en presencia de mis angustiadores; unges mi cabeza con aceite; mi copa está rebosando."},
        {"verse": 6, "text": "Ciertamente el bien y la misericordia me seguirán todos los días de mi vida, y en la casa de Jehová moraré por largos días."},
    ],
    "Salmos:91": [
        {"verse": 1, "text": "El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente."},
        {"verse": 2, "text": "Diré yo a Jehová: Esperanza mía, y castillo mío; mi Dios, en quien confiaré."},
        {"verse": 3, "text": "El te librará del lazo del cazador, de la peste destructora."},
        {"verse": 4, "text": "Con sus plumas te cubrirá, y debajo de sus alas estarás seguro; escudo y adarga es su verdad."},
        {"verse": 5, "text": "No temerás el terror nocturno, ni saeta que vuele de día,"},
        {"verse": 6, "text": "Ni pestilencia que ande en oscuridad, ni mortandad que en medio del día destruya."},
        {"verse": 7, "text": "Caerán a tu lado mil, y diez mil a tu diestra; mas a ti no llegará."},
        {"verse": 11, "text": "Pues a sus ángeles mandará acerca de ti, que te guarden en todos tus caminos."},
        {"verse": 12, "text": "En las manos te llevarán, para que tu pie no tropiece en piedra."},
    ],
    # JUAN
    "Juan:3": [
        {"verse": 1, "text": "Había un hombre de los fariseos que se llamaba Nicodemo, un principal entre los judíos."},
        {"verse": 2, "text": "Este vino a Jesús de noche, y le dijo: Rabí, sabemos que has venido de Dios como maestro; porque nadie puede hacer estas señales que tú haces, si no está Dios con él."},
        {"verse": 3, "text": "Respondió Jesús y le dijo: De cierto, de cierto te digo, que el que no naciere de nuevo, no puede ver el reino de Dios."},
        {"verse": 14, "text": "Y como Moisés levantó la serpiente en el desierto, así es necesario que el Hijo del Hombre sea levantado,"},
        {"verse": 15, "text": "para que todo aquel que en él cree, no se pierda, mas tenga vida eterna."},
        {"verse": 16, "text": "Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna."},
        {"verse": 17, "text": "Porque no envió Dios a su Hijo al mundo para condenar al mundo, sino para que el mundo sea salvo por él."},
    ],
    "Juan:14": [
        {"verse": 1, "text": "No se turbe vuestro corazón; creéis en Dios, creed también en mí."},
        {"verse": 2, "text": "En la casa de mi Padre muchas moradas hay; si así no fuera, yo os lo hubiera dicho; voy, pues, a preparar lugar para vosotros."},
        {"verse": 3, "text": "Y si me fuere y os preparare lugar, vendré otra vez, y os tomaré a mí mismo, para que donde yo estoy, vosotros también estéis."},
        {"verse": 6, "text": "Jesús le dijo: Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí."},
        {"verse": 27, "text": "La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo."},
    ],
    # ROMANOS
    "Romanos:8": [
        {"verse": 1, "text": "Ahora, pues, ninguna condenación hay para los que están en Cristo Jesús, los que no andan conforme a la carne, sino conforme al Espíritu."},
        {"verse": 28, "text": "Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados."},
        {"verse": 31, "text": "¿Qué, pues, diremos a esto? Si Dios es por nosotros, ¿quién contra nosotros?"},
        {"verse": 37, "text": "Antes, en todas estas cosas somos más que vencedores por medio de aquel que nos amó."},
        {"verse": 38, "text": "Por lo cual estoy seguro de que ni la muerte, ni la vida, ni ángeles, ni principados, ni potestades, ni lo presente, ni lo por venir,"},
        {"verse": 39, "text": "ni lo alto, ni lo profundo, ni ninguna otra cosa creada nos podrá separar del amor de Dios, que es en Cristo Jesús Señor nuestro."},
    ],
    # FILIPENSES
    "Filipenses:4": [
        {"verse": 4, "text": "Regocijaos en el Señor siempre. Otra vez digo: ¡Regocijaos!"},
        {"verse": 6, "text": "Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias."},
        {"verse": 7, "text": "Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús."},
        {"verse": 13, "text": "Todo lo puedo en Cristo que me fortalece."},
        {"verse": 19, "text": "Mi Dios, pues, suplirá todo lo que os falta conforme a sus riquezas en gloria en Cristo Jesús."},
    ],
    # MATEO
    "Mateo:5": [
        {"verse": 3, "text": "Bienaventurados los pobres en espíritu, porque de ellos es el reino de los cielos."},
        {"verse": 4, "text": "Bienaventurados los que lloran, porque ellos recibirán consolación."},
        {"verse": 5, "text": "Bienaventurados los mansos, porque ellos recibirán la tierra por heredad."},
        {"verse": 6, "text": "Bienaventurados los que tienen hambre y sed de justicia, porque ellos serán saciados."},
        {"verse": 7, "text": "Bienaventurados los misericordiosos, porque ellos alcanzarán misericordia."},
        {"verse": 8, "text": "Bienaventurados los de limpio corazón, porque ellos verán a Dios."},
        {"verse": 9, "text": "Bienaventurados los pacificadores, porque ellos serán llamados hijos de Dios."},
        {"verse": 14, "text": "Vosotros sois la luz del mundo; una ciudad asentada sobre un monte no se puede esconder."},
        {"verse": 16, "text": "Así alumbre vuestra luz delante de los hombres, para que vean vuestras buenas obras, y glorifiquen a vuestro Padre que está en los cielos."},
    ],
    "Mateo:6": [
        {"verse": 9, "text": "Vosotros, pues, oraréis así: Padre nuestro que estás en los cielos, santificado sea tu nombre."},
        {"verse": 10, "text": "Venga tu reino. Hágase tu voluntad, como en el cielo, así también en la tierra."},
        {"verse": 11, "text": "El pan nuestro de cada día, dánoslo hoy."},
        {"verse": 12, "text": "Y perdónanos nuestras deudas, como también nosotros perdonamos a nuestros deudores."},
        {"verse": 13, "text": "Y no nos metas en tentación, mas líbranos del mal; porque tuyo es el reino, y el poder, y la gloria, por todos los siglos. Amén."},
        {"verse": 33, "text": "Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas."},
    ],
    # PROVERBIOS
    "Proverbios:3": [
        {"verse": 5, "text": "Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia."},
        {"verse": 6, "text": "Reconócelo en todos tus caminos, y él enderezará tus veredas."},
    ],
    # APOCALIPSIS
    "Apocalipsis:21": [
        {"verse": 1, "text": "Vi un cielo nuevo y una tierra nueva; porque el primer cielo y la primera tierra pasaron, y el mar ya no existía más."},
        {"verse": 4, "text": "Enjugará Dios toda lágrima de los ojos de ellos; y ya no habrá muerte, ni habrá más llanto, ni clamor, ni dolor; porque las primeras cosas pasaron."},
        {"verse": 5, "text": "Y el que estaba sentado en el trono dijo: He aquí, yo hago nuevas todas las cosas."},
    ],
}

# Function to get chapter by book name and language
def get_bible_chapter(book: str, chapter: int, lang: str = "it") -> list:
    """Get verses for a specific chapter"""
    key = f"{book}:{chapter}"
    
    if lang == "it":
        return NUOVA_DIODATI.get(key, [])
    elif lang == "es":
        return REINA_VALERA_1960.get(key, [])
    
    # Try to find equivalent in Italian first
    return NUOVA_DIODATI.get(key, [])
