import { create } from 'zustand';
import AsyncStorage from '@react-native-async-storage/async-storage';

interface Language {
  name: string;
  flag: string;
  tts_code: string;
}

interface LanguageState {
  currentLanguage: string;
  languages: Record<string, Language>;
  setLanguage: (lang: string) => Promise<void>;
  loadLanguage: () => Promise<void>;
  loadLanguages: () => Promise<void>;
}

const API_URL = process.env.EXPO_PUBLIC_BACKEND_URL || '';

export const useLanguageStore = create<LanguageState>((set, get) => ({
  currentLanguage: 'it',
  languages: {
    it: { name: 'Italiano', flag: '🇮🇹', tts_code: 'it-IT' },
    es: { name: 'Español', flag: '🇪🇸', tts_code: 'es-ES' },
    en: { name: 'English', flag: '🇬🇧', tts_code: 'en-US' },
    pt: { name: 'Português', flag: '🇧🇷', tts_code: 'pt-BR' },
    fr: { name: 'Français', flag: '🇫🇷', tts_code: 'fr-FR' },
    de: { name: 'Deutsch', flag: '🇩🇪', tts_code: 'de-DE' },
  },

  setLanguage: async (lang: string) => {
    await AsyncStorage.setItem('app_language', lang);
    set({ currentLanguage: lang });
  },

  loadLanguage: async () => {
    const saved = await AsyncStorage.getItem('app_language');
    if (saved) {
      set({ currentLanguage: saved });
    }
  },

  loadLanguages: async () => {
    try {
      const response = await fetch(`${API_URL}/api/languages`);
      if (response.ok) {
        const data = await response.json();
        set({ languages: data });
      }
    } catch (error) {
      console.log('Error loading languages:', error);
    }
  },
}));

// UI Translations
export const translations: Record<string, Record<string, string>> = {
  it: {
    welcome: 'Benvenuto',
    goodMorning: 'Buongiorno',
    goodAfternoon: 'Buon pomeriggio',
    goodEvening: 'Buonasera',
    dailyVerse: 'Versetto del Giorno',
    howAreYou: 'Come ti senti oggi?',
    quickActions: 'Azioni Rapide',
    read: 'Leggi',
    write: 'Scrivi',
    ask: 'Chiedi',
    theBible: 'La Bibbia',
    inJournal: 'Nel Diario',
    toAssistant: "All'Assistente",
    yourProgress: 'Il Tuo Progresso',
    daysInRow: 'Giorni di fila',
    chaptersRead: 'Capitoli letti',
    journalEntries: 'Voci diario',
    community: 'Community',
    translate: 'Traduci',
    send: 'Invia',
    login: 'Accedi',
    register: 'Registrati',
    logout: 'Esci',
    settings: 'Impostazioni',
    language: 'Lingua',
    profile: 'Profilo',
    home: 'Home',
    bible: 'Bibbia',
    journal: 'Diario',
    assistant: 'Assistente',
    donate: 'Dona',
    radios: 'Radio Evangeliche',
    explore: 'Esplora',
    quizzes: 'Quiz Biblici',
    dictionary: 'Dizionario',
    forum: 'Forum',
    maps: 'Mappe',
    liveEvents: 'Eventi Live',
    worldwide: 'Mondiale',
    error: 'Errore',
    loadError: 'Impossibile caricare',
    submitError: 'Impossibile inviare',
    save: 'Salva',
    cancel: 'Annulla',
    delete: 'Elimina',
    confirm: 'Conferma',
    yourName: 'Il tuo nome',
    appLanguage: 'Lingua dell\'app',
    preferredEdition: 'Edizione preferita',
    pushNotifications: 'Notifiche Push',
    receiveNotifications: 'Ricevi notifiche dalla community',
    dailyVerseNotification: 'Versetto del Giorno',
    receiveVerse: 'Ricevi un versetto ogni mattina',
    info: 'Informazioni',
    appVersion: 'Versione app',
    privacyLegal: 'Privacy e Legale',
    privacyPolicy: 'Informativa sulla Privacy',
    termsOfService: 'Termini di Servizio',
    gdprConsents: 'Gestione Consensi GDPR',
    deleteAccount: 'Elimina Account',
    logoutAccount: 'Esci dall\'Account',
    disconnectConfirm: 'Vuoi uscire dal tuo account?',
    deleteConfirm: 'Sei sicuro di voler eliminare il tuo account? Questa azione è irreversibile.',
    saved: 'Salvato!',
    settingsUpdated: 'Le tue impostazioni sono state aggiornate.',
    brother: 'Fratello',
    sister: 'Sorella',
    noQuizzesAvailable: 'Nessun quiz disponibile',
    advancedComingSoon: 'Quiz avanzati disponibili prossimamente',
    // Bible screen
    loadingBooks: 'Caricamento libri...',
    noBooksAvailable: 'Nessun libro disponibile',
    retry: 'Riprova',
    chapters: 'capitoli',
    editions: 'Edizioni',
    help: 'Aiuto',
    studyContextAvailable: 'Contesto di studio disponibile',
    yourNotes: 'I tuoi appunti',
    addChapterNote: 'Aggiungi nota al capitolo',
    note: 'Nota',
    aiExplain: 'AI Spiega',
    highlight: 'Evidenzia',
    share: 'Condividi',
    bookmark: 'Segnalibro',
    crossReferences: 'Riferimenti Incrociati',
    dictionaryTerms: 'Termini nel Dizionario',
    historicalContext: 'Contesto Storico',
    literaryStructure: 'Struttura Letteraria',
    keyThemes: 'Temi Chiave',
    application: 'Applicazione',
    noteToChapter: 'Nota al Capitolo',
    writeYourNotes: 'Scrivi i tuoi appunti...',
    saveNote: 'Salva Nota',
    aiExplanation: 'AI Spiegazione',
    askSpecificQuestion: 'Fai una domanda specifica (opzionale)...',
    askAi: 'Chiedi all\'AI',
    selectBibleEdition: 'Seleziona Edizione Biblica',
    selectLanguage: 'Seleziona Lingua',
    readingGuide: 'Guida alla Lettura',
    changeLanguage: 'Cambia Lingua',
    changeLanguageDesc: 'Tocca le bandiere in alto per cambiare la lingua della Bibbia in qualsiasi momento.',
    bibleTranslations: 'Traduzioni Bibliche',
    bibleTranslationsDesc: 'Il banner in alto mostra quale traduzione stai leggendo.',
    tapVerse: 'Tocca un Versetto',
    tapVerseDesc: 'Tocca qualsiasi versetto per aprire gli strumenti di studio.',
    textSize: 'Dimensione Testo',
    textSizeDesc: 'Tocca il pulsante A per aumentare la dimensione del testo.',
    listen: 'Ascolta',
    listenDesc: 'Tocca l\'icona dell\'altoparlante per ascoltare la lettura del capitolo.',
    understood: 'Ho Capito!',
    // Settings
    disconnect: 'Disconnetti',
    accountDeleted: 'Account eliminato con successo',
    deleteAccountError: 'Impossibile eliminare l\'account. Riprova più tardi.',
    notifications: 'Notifiche',
    email: 'E-mail',
    // Bible screen additional
    verseFromBible: 'Versetto dalla Bibbia',
    unableToShare: 'Impossibile condividere',
    unableToOpenWikipedia: 'Impossibile aprire Wikipedia',
    noteSavedSuccess: 'Nota aggiunta con successo',
    unableToSaveNote: 'Impossibile salvare la nota',
    unableToGetExplanation: 'Impossibile ottenere la spiegazione',
    unableToOpenLaParola: 'Impossibile aprire LaParola',
    theBibleHeader: 'La Bibbia',
    selectEdition: 'Seleziona edizione',
    study: 'Studio',
    wikipedia: 'Wikipedia',
    laParola: 'LaParola',
    personalNotes: 'Aggiungi note personali',
    shareWithFriends: 'Condividi con amici',
    saveToBookmarks: 'Salva nei segnalibri',
    explainWithAI: 'Chiedi spiegazione all\'AI',
    highlightVerse: 'Evidenzia il versetto',
    // Common messages
    noMessagesYet: 'Nessun messaggio',
    shareThought: 'Condividi un pensiero, una preghiera...',
    noPostsYet: 'Nessun post ancora',
    noGroupsFound: 'Nessun gruppo trovato',
    notInAnyGroup: 'Non sei ancora in nessun gruppo',
    unableToVote: 'Impossibile votare',
    fillAllFields: 'Compila tutti i campi',
    unableToCreatePost: 'Impossibile creare il post',
    selectYourMood: 'Seleziona il tuo stato d\'animo per ricevere una parola personalizzata',
    paypalNotAvailable: 'Link PayPal non disponibile',
    enterAmountAndMethod: 'Inserisci un importo e seleziona un metodo',
    selectAmount: 'Seleziona Importo',
    noResults: 'Nessun risultato trovato',
    enterMessage: 'Inserisci un messaggio',
    unableToSendMessage: 'Impossibile inviare il messaggio',
    unableToSubscribe: 'Impossibile iscriversi',
    unableToCreateEvent: 'Impossibile creare l\'evento',
    noEventsScheduled: 'Nessun evento in programma',
    shareYourHeart: 'Condividi il tuo cuore con Dio',
    noFlashcards: 'Nessuna flashcard',
    noFlashcardsDesc: 'Aggiungi termini dal dizionario per iniziare a studiare',
    unableToOpenRadio: 'Impossibile aprire il link della radio',
    loadingRadios: 'Caricamento radio...',
    noRadiosFound: 'Nessuna radio trovata',
    writeInJournal: 'Scrivi qualcosa nel diario',
    selectMood: 'Seleziona il tuo stato d\'animo',
    journalSaved: 'La tua voce è stata salvata nel diario',
    addToFavorites: 'Aggiungi ai Preferiti',
    noFavoritesSaved: 'Nessun preferito salvato',
    // Community and Forum
    prayer: 'Preghiera',
    original: 'Originale',
    connectWithBrothers: 'Connettiti con fratelli nel mondo',
    beFirstToShare: 'Sii il primo a condividere!',
    communityForum: 'Forum Comunitario',
    all: 'Tutti',
    newPost: 'Nuovo Post',
    category: 'Categoria',
    title: 'Titolo',
    content: 'Contenuto',
    postTitlePlaceholder: 'Titolo del post...',
    writeYourMessage: 'Scrivi il tuo messaggio...',
    publish: 'Pubblica',
    published: 'Pubblicato!',
    postCreated: 'Il tuo post è stato creato',
    beFirstToPost: 'Sii il primo a pubblicare!',
    // Radio
    evangelicalRadios: 'Radio Evangeliche',
    allRadios: 'Tutte le Radio',
    favorites: 'Preferiti',
    // Continents
    europe: 'Europa',
    southAmerica: 'Sud America',
    northAmerica: 'Nord America',
    africa: 'Africa',
    asia: 'Asia',
    oceania: 'Oceania',
    // Moods
    moodHappy: 'Felice',
    moodSad: 'Triste',
    moodAnxious: 'Ansioso',
    moodAngry: 'Arrabbiato',
    moodGrateful: 'Grato',
    moodConfused: 'Confuso',
    moodHopeful: 'Speranzoso',
    moodTired: 'Stanco',
    // Auth screens
    createAccount: 'Crea Account',
    startSpiritualJourney: 'Inizia il tuo viaggio spirituale',
    fullName: 'Nome completo',
    confirmPassword: 'Conferma password',
    alreadyHaveAccount: 'Hai già un account?',
    noAccount: 'Non hai un account?',
    loginButton: 'Accedi',
    registerButton: 'Registrati',
    orDivider: 'oppure',
    continueWithGoogle: 'Continua con Google',
    dailySpiritualCompanion: 'Il tuo compagno spirituale quotidiano',
    fillAllFieldsError: 'Compila tutti i campi',
    passwordMismatchError: 'Le password non corrispondono',
    passwordMinLengthError: 'La password deve avere almeno 6 caratteri',
    enterEmailPassword: 'Inserisci email e password',
    registrationFailed: 'Registrazione fallita',
    loginFailed: 'Login fallito',
    googleSessionNotFound: 'Sessione Google non trovata. Riprova.',
    googleLoginFailed: 'Login Google fallito. Verifica la connessione.',
    // Biometric
    enableBiometric: 'Abilita accesso con impronta',
    biometricLogin: 'Accedi con impronta',
    biometricPrompt: 'Conferma la tua identità',
    biometricSuccess: 'Autenticazione riuscita',
    biometricFailed: 'Autenticazione biometrica fallita',
    biometricNotAvailable: 'Autenticazione biometrica non disponibile',
    rememberCredentials: 'Ricorda credenziali',
    usePassword: 'Usa password',
    // Terms and Conditions
    iAccept: 'Accetto i',
    termsAndConditions: 'Termini e Condizioni',
    acceptTermsRequired: 'Devi accettare i Termini e le Condizioni per registrarti',
    readBible: 'Leggi Bibbia',
    quiz: 'Quiz',
    groups: 'Gruppi',
    onlineNow: 'Online ora',
    onlineUsers: 'Utenti online',
    you: 'Tu',
    startConversation: 'Inizia la conversazione!',
    writeYourMessage: 'Scrivi il tuo messaggio...',
    unableToSendMessage: 'Impossibile inviare il messaggio',
  },
  es: {
    welcome: 'Bienvenido',
    goodMorning: 'Buenos días',
    goodAfternoon: 'Buenas tardes',
    goodEvening: 'Buenas noches',
    dailyVerse: 'Versículo del Día',
    howAreYou: '¿Cómo te sientes hoy?',
    quickActions: 'Acciones Rápidas',
    read: 'Leer',
    write: 'Escribir',
    ask: 'Preguntar',
    theBible: 'La Biblia',
    inJournal: 'En el Diario',
    toAssistant: 'Al Asistente',
    yourProgress: 'Tu Progreso',
    daysInRow: 'Días seguidos',
    chaptersRead: 'Capítulos leídos',
    journalEntries: 'Entradas del diario',
    community: 'Comunidad',
    translate: 'Traducir',
    send: 'Enviar',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    logout: 'Salir',
    settings: 'Configuración',
    language: 'Idioma',
    profile: 'Perfil',
    home: 'Inicio',
    bible: 'Biblia',
    journal: 'Diario',
    assistant: 'Asistente',
    donate: 'Donar',
    radios: 'Radios Evangélicas',
    explore: 'Explorar',
    quizzes: 'Quiz Bíblicos',
    dictionary: 'Diccionario',
    forum: 'Foro',
    maps: 'Mapas',
    liveEvents: 'Eventos en Vivo',
    worldwide: 'Mundial',
    error: 'Error',
    loadError: 'No se puede cargar',
    submitError: 'No se puede enviar',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    confirm: 'Confirmar',
    yourName: 'Tu nombre',
    appLanguage: 'Idioma de la app',
    preferredEdition: 'Edición preferida',
    pushNotifications: 'Notificaciones Push',
    receiveNotifications: 'Recibir notificaciones de la comunidad',
    dailyVerseNotification: 'Versículo del Día',
    receiveVerse: 'Recibir un versículo cada mañana',
    info: 'Información',
    appVersion: 'Versión de la app',
    privacyLegal: 'Privacidad y Legal',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    gdprConsents: 'Gestión de Consentimientos GDPR',
    deleteAccount: 'Eliminar Cuenta',
    logoutAccount: 'Cerrar Sesión',
    disconnectConfirm: '¿Quieres salir de tu cuenta?',
    deleteConfirm: '¿Estás seguro de que deseas eliminar tu cuenta? Esta acción es irreversible.',
    saved: '¡Guardado!',
    settingsUpdated: 'Tu configuración ha sido actualizada.',
    brother: 'Hermano',
    sister: 'Hermana',
    noQuizzesAvailable: 'No hay quiz disponibles',
    advancedComingSoon: 'Quiz avanzados disponibles próximamente',
    // Bible screen
    loadingBooks: 'Cargando libros...',
    noBooksAvailable: 'No hay libros disponibles',
    retry: 'Reintentar',
    chapters: 'capítulos',
    editions: 'Ediciones',
    help: 'Ayuda',
    studyContextAvailable: 'Contexto de estudio disponible',
    yourNotes: 'Tus notas',
    addChapterNote: 'Añadir nota al capítulo',
    note: 'Nota',
    aiExplain: 'IA Explica',
    highlight: 'Resaltar',
    share: 'Compartir',
    bookmark: 'Marcador',
    crossReferences: 'Referencias Cruzadas',
    dictionaryTerms: 'Términos del Diccionario',
    historicalContext: 'Contexto Histórico',
    literaryStructure: 'Estructura Literaria',
    keyThemes: 'Temas Clave',
    application: 'Aplicación',
    noteToChapter: 'Nota al Capítulo',
    writeYourNotes: 'Escribe tus notas...',
    saveNote: 'Guardar Nota',
    aiExplanation: 'Explicación de IA',
    askSpecificQuestion: 'Haz una pregunta específica (opcional)...',
    askAi: 'Preguntar a la IA',
    selectBibleEdition: 'Seleccionar Edición Bíblica',
    selectLanguage: 'Seleccionar Idioma',
    readingGuide: 'Guía de Lectura',
    changeLanguage: 'Cambiar Idioma',
    changeLanguageDesc: 'Toca las banderas de arriba para cambiar el idioma de la Biblia.',
    bibleTranslations: 'Traducciones Bíblicas',
    bibleTranslationsDesc: 'El banner de arriba muestra qué traducción estás leyendo.',
    tapVerse: 'Toca un Versículo',
    tapVerseDesc: 'Toca cualquier versículo para abrir las herramientas de estudio.',
    textSize: 'Tamaño del Texto',
    textSizeDesc: 'Toca el botón A para aumentar el tamaño del texto.',
    listen: 'Escuchar',
    listenDesc: 'Toca el icono del altavoz para escuchar la lectura del capítulo.',
    understood: '¡Entendido!',
    disconnect: 'Desconectar',
    accountDeleted: 'Cuenta eliminada con éxito',
    deleteAccountError: 'No se puede eliminar la cuenta. Inténtalo más tarde.',
    notifications: 'Notificaciones',
    email: 'Correo electrónico',
    // Bible screen additional
    verseFromBible: 'Versículo de la Biblia',
    unableToShare: 'No se puede compartir',
    unableToOpenWikipedia: 'No se puede abrir Wikipedia',
    noteSavedSuccess: 'Nota añadida con éxito',
    unableToSaveNote: 'No se puede guardar la nota',
    unableToGetExplanation: 'No se puede obtener la explicación',
    unableToOpenLaParola: 'No se puede abrir LaParola',
    theBibleHeader: 'La Biblia',
    selectEdition: 'Seleccionar edición',
    study: 'Estudio',
    wikipedia: 'Wikipedia',
    laParola: 'LaParola',
    personalNotes: 'Añadir notas personales',
    shareWithFriends: 'Compartir con amigos',
    saveToBookmarks: 'Guardar en marcadores',
    explainWithAI: 'Pedir explicación a la IA',
    highlightVerse: 'Resaltar el versículo',
    // Common messages
    noMessagesYet: 'Sin mensajes',
    shareThought: 'Comparte un pensamiento, una oración...',
    noPostsYet: 'Aún no hay publicaciones',
    noGroupsFound: 'No se encontraron grupos',
    notInAnyGroup: 'Aún no estás en ningún grupo',
    unableToVote: 'No se puede votar',
    fillAllFields: 'Completa todos los campos',
    unableToCreatePost: 'No se puede crear la publicación',
    selectYourMood: 'Selecciona tu estado de ánimo para recibir una palabra personalizada',
    paypalNotAvailable: 'Enlace de PayPal no disponible',
    enterAmountAndMethod: 'Introduce un importe y selecciona un método',
    selectAmount: 'Seleccionar Importe',
    noResults: 'No se encontraron resultados',
    enterMessage: 'Introduce un mensaje',
    unableToSendMessage: 'No se puede enviar el mensaje',
    unableToSubscribe: 'No se puede suscribir',
    unableToCreateEvent: 'No se puede crear el evento',
    noEventsScheduled: 'No hay eventos programados',
    shareYourHeart: 'Comparte tu corazón con Dios',
    noFlashcards: 'Sin flashcards',
    noFlashcardsDesc: 'Añade términos del diccionario para empezar a estudiar',
    unableToOpenRadio: 'No se puede abrir el enlace de la radio',
    loadingRadios: 'Cargando radios...',
    noRadiosFound: 'No se encontraron radios',
    writeInJournal: 'Escribe algo en el diario',
    selectMood: 'Selecciona tu estado de ánimo',
    journalSaved: 'Tu entrada ha sido guardada en el diario',
    addToFavorites: 'Añadir a Favoritos',
    noFavoritesSaved: 'Sin favoritos guardados',
    // Community and Forum
    prayer: 'Oración',
    original: 'Original',
    connectWithBrothers: 'Conéctate con hermanos en el mundo',
    beFirstToShare: '¡Sé el primero en compartir!',
    communityForum: 'Foro Comunitario',
    all: 'Todos',
    newPost: 'Nueva Publicación',
    category: 'Categoría',
    title: 'Título',
    content: 'Contenido',
    postTitlePlaceholder: 'Título de la publicación...',
    writeYourMessage: 'Escribe tu mensaje...',
    publish: 'Publicar',
    published: '¡Publicado!',
    postCreated: 'Tu publicación ha sido creada',
    beFirstToPost: '¡Sé el primero en publicar!',
    // Radio
    evangelicalRadios: 'Radios Evangélicas',
    allRadios: 'Todas las Radios',
    favorites: 'Favoritos',
    // Continents
    europe: 'Europa',
    southAmerica: 'Sudamérica',
    northAmerica: 'Norteamérica',
    africa: 'África',
    asia: 'Asia',
    oceania: 'Oceanía',
    // Moods
    moodHappy: 'Feliz',
    moodSad: 'Triste',
    moodAnxious: 'Ansioso',
    moodAngry: 'Enojado',
    moodGrateful: 'Agradecido',
    moodConfused: 'Confundido',
    moodHopeful: 'Esperanzado',
    moodTired: 'Cansado',
    // Auth screens
    createAccount: 'Crear Cuenta',
    startSpiritualJourney: 'Comienza tu viaje espiritual',
    fullName: 'Nombre completo',
    confirmPassword: 'Confirmar contraseña',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    noAccount: '¿No tienes una cuenta?',
    loginButton: 'Iniciar sesión',
    registerButton: 'Registrarse',
    orDivider: 'o',
    continueWithGoogle: 'Continuar con Google',
    dailySpiritualCompanion: 'Tu compañero espiritual diario',
    fillAllFieldsError: 'Completa todos los campos',
    passwordMismatchError: 'Las contraseñas no coinciden',
    passwordMinLengthError: 'La contraseña debe tener al menos 6 caracteres',
    enterEmailPassword: 'Introduce correo y contraseña',
    registrationFailed: 'Registro fallido',
    loginFailed: 'Inicio de sesión fallido',
    googleSessionNotFound: 'Sesión de Google no encontrada. Inténtalo de nuevo.',
    googleLoginFailed: 'Login de Google fallido. Verifica la conexión.',
    // Biometric
    enableBiometric: 'Habilitar acceso con huella',
    biometricLogin: 'Acceder con huella',
    biometricPrompt: 'Confirma tu identidad',
    biometricSuccess: 'Autenticación exitosa',
    biometricFailed: 'Autenticación biométrica fallida',
    biometricNotAvailable: 'Autenticación biométrica no disponible',
    rememberCredentials: 'Recordar credenciales',
    usePassword: 'Usar contraseña',
    // Terms and Conditions
    iAccept: 'Acepto los',
    termsAndConditions: 'Términos y Condiciones',
    acceptTermsRequired: 'Debes aceptar los Términos y Condiciones para registrarte',
    readBible: 'Leer Biblia',
    quiz: 'Quiz',
    groups: 'Grupos',
    onlineNow: 'En línea ahora',
    onlineUsers: 'Usuarios en línea',
    you: 'Tú',
    startConversation: '¡Inicia la conversación!',
    writeYourMessage: 'Escribe tu mensaje...',
    unableToSendMessage: 'No se pudo enviar el mensaje',
  },
  en: {
    welcome: 'Welcome',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    dailyVerse: 'Daily Verse',
    howAreYou: 'How are you feeling today?',
    quickActions: 'Quick Actions',
    read: 'Read',
    write: 'Write',
    ask: 'Ask',
    theBible: 'The Bible',
    inJournal: 'In Journal',
    toAssistant: 'the Assistant',
    yourProgress: 'Your Progress',
    daysInRow: 'Days in a row',
    chaptersRead: 'Chapters read',
    journalEntries: 'Journal entries',
    community: 'Community',
    translate: 'Translate',
    send: 'Send',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    settings: 'Settings',
    language: 'Language',
    profile: 'Profile',
    home: 'Home',
    bible: 'Bible',
    journal: 'Journal',
    assistant: 'Assistant',
    donate: 'Donate',
    radios: 'Evangelical Radios',
    explore: 'Explore',
    quizzes: 'Bible Quizzes',
    dictionary: 'Dictionary',
    forum: 'Forum',
    maps: 'Maps',
    liveEvents: 'Live Events',
    worldwide: 'Worldwide',
    error: 'Error',
    loadError: 'Unable to load',
    submitError: 'Unable to submit',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    yourName: 'Your name',
    appLanguage: 'App language',
    preferredEdition: 'Preferred edition',
    pushNotifications: 'Push Notifications',
    receiveNotifications: 'Receive notifications from the community',
    dailyVerseNotification: 'Daily Verse',
    receiveVerse: 'Receive a verse every morning',
    info: 'Information',
    appVersion: 'App version',
    privacyLegal: 'Privacy & Legal',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    gdprConsents: 'GDPR Consent Management',
    deleteAccount: 'Delete Account',
    logoutAccount: 'Logout',
    disconnectConfirm: 'Do you want to log out of your account?',
    deleteConfirm: 'Are you sure you want to delete your account? This action is irreversible.',
    saved: 'Saved!',
    settingsUpdated: 'Your settings have been updated.',
    brother: 'Brother',
    sister: 'Sister',
    noQuizzesAvailable: 'No quizzes available',
    advancedComingSoon: 'Advanced quizzes coming soon',
    // Bible screen
    loadingBooks: 'Loading books...',
    noBooksAvailable: 'No books available',
    retry: 'Retry',
    chapters: 'chapters',
    editions: 'Editions',
    help: 'Help',
    studyContextAvailable: 'Study context available',
    yourNotes: 'Your notes',
    addChapterNote: 'Add chapter note',
    note: 'Note',
    aiExplain: 'AI Explain',
    highlight: 'Highlight',
    share: 'Share',
    bookmark: 'Bookmark',
    crossReferences: 'Cross References',
    dictionaryTerms: 'Dictionary Terms',
    historicalContext: 'Historical Context',
    literaryStructure: 'Literary Structure',
    keyThemes: 'Key Themes',
    application: 'Application',
    noteToChapter: 'Chapter Note',
    writeYourNotes: 'Write your notes...',
    saveNote: 'Save Note',
    aiExplanation: 'AI Explanation',
    askSpecificQuestion: 'Ask a specific question (optional)...',
    askAi: 'Ask AI',
    selectBibleEdition: 'Select Bible Edition',
    selectLanguage: 'Select Language',
    readingGuide: 'Reading Guide',
    changeLanguage: 'Change Language',
    changeLanguageDesc: 'Tap the flags above to change the Bible language anytime.',
    bibleTranslations: 'Bible Translations',
    bibleTranslationsDesc: 'The banner above shows which translation you are reading.',
    tapVerse: 'Tap a Verse',
    tapVerseDesc: 'Tap any verse to open the study tools.',
    textSize: 'Text Size',
    textSizeDesc: 'Tap the A button to increase text size.',
    listen: 'Listen',
    listenDesc: 'Tap the speaker icon to listen to the chapter being read.',
    understood: 'Got It!',
    disconnect: 'Disconnect',
    accountDeleted: 'Account deleted successfully',
    deleteAccountError: 'Unable to delete account. Try again later.',
    notifications: 'Notifications',
    email: 'Email',
    // Bible screen additional
    verseFromBible: 'Bible Verse',
    unableToShare: 'Unable to share',
    unableToOpenWikipedia: 'Unable to open Wikipedia',
    noteSavedSuccess: 'Note added successfully',
    unableToSaveNote: 'Unable to save note',
    unableToGetExplanation: 'Unable to get explanation',
    unableToOpenLaParola: 'Unable to open LaParola',
    theBibleHeader: 'The Bible',
    selectEdition: 'Select edition',
    study: 'Study',
    wikipedia: 'Wikipedia',
    laParola: 'LaParola',
    personalNotes: 'Add personal notes',
    shareWithFriends: 'Share with friends',
    saveToBookmarks: 'Save to bookmarks',
    explainWithAI: 'Ask AI for explanation',
    highlightVerse: 'Highlight verse',
    // Common messages
    noMessagesYet: 'No messages',
    shareThought: 'Share a thought, a prayer...',
    noPostsYet: 'No posts yet',
    noGroupsFound: 'No groups found',
    notInAnyGroup: 'You are not in any group yet',
    unableToVote: 'Unable to vote',
    fillAllFields: 'Fill in all fields',
    unableToCreatePost: 'Unable to create post',
    selectYourMood: 'Select your mood to receive a personalized word',
    paypalNotAvailable: 'PayPal link not available',
    enterAmountAndMethod: 'Enter an amount and select a method',
    selectAmount: 'Select Amount',
    noResults: 'No results found',
    enterMessage: 'Enter a message',
    unableToSendMessage: 'Unable to send message',
    unableToSubscribe: 'Unable to subscribe',
    unableToCreateEvent: 'Unable to create event',
    noEventsScheduled: 'No events scheduled',
    shareYourHeart: 'Share your heart with God',
    noFlashcards: 'No flashcards',
    noFlashcardsDesc: 'Add terms from the dictionary to start studying',
    unableToOpenRadio: 'Unable to open radio link',
    loadingRadios: 'Loading radios...',
    noRadiosFound: 'No radios found',
    writeInJournal: 'Write something in the journal',
    selectMood: 'Select your mood',
    journalSaved: 'Your entry has been saved to the journal',
    addToFavorites: 'Add to Favorites',
    noFavoritesSaved: 'No favorites saved',
    // Community and Forum
    prayer: 'Prayer',
    original: 'Original',
    connectWithBrothers: 'Connect with brothers around the world',
    beFirstToShare: 'Be the first to share!',
    communityForum: 'Community Forum',
    all: 'All',
    newPost: 'New Post',
    category: 'Category',
    title: 'Title',
    content: 'Content',
    postTitlePlaceholder: 'Post title...',
    writeYourMessage: 'Write your message...',
    publish: 'Publish',
    published: 'Published!',
    postCreated: 'Your post has been created',
    beFirstToPost: 'Be the first to post!',
    // Radio
    evangelicalRadios: 'Evangelical Radios',
    allRadios: 'All Radios',
    favorites: 'Favorites',
    // Continents
    europe: 'Europe',
    southAmerica: 'South America',
    northAmerica: 'North America',
    africa: 'Africa',
    asia: 'Asia',
    oceania: 'Oceania',
    // Moods
    moodHappy: 'Happy',
    moodSad: 'Sad',
    moodAnxious: 'Anxious',
    moodAngry: 'Angry',
    moodGrateful: 'Grateful',
    moodConfused: 'Confused',
    moodHopeful: 'Hopeful',
    moodTired: 'Tired',
    // Auth screens
    createAccount: 'Create Account',
    startSpiritualJourney: 'Start your spiritual journey',
    fullName: 'Full name',
    confirmPassword: 'Confirm password',
    alreadyHaveAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    loginButton: 'Login',
    registerButton: 'Register',
    orDivider: 'or',
    continueWithGoogle: 'Continue with Google',
    dailySpiritualCompanion: 'Your daily spiritual companion',
    fillAllFieldsError: 'Fill in all fields',
    passwordMismatchError: 'Passwords do not match',
    passwordMinLengthError: 'Password must be at least 6 characters',
    enterEmailPassword: 'Enter email and password',
    registrationFailed: 'Registration failed',
    loginFailed: 'Login failed',
    googleSessionNotFound: 'Google session not found. Try again.',
    googleLoginFailed: 'Google login failed. Check your connection.',
    // Biometric
    enableBiometric: 'Enable fingerprint login',
    biometricLogin: 'Login with fingerprint',
    biometricPrompt: 'Confirm your identity',
    biometricSuccess: 'Authentication successful',
    biometricFailed: 'Biometric authentication failed',
    biometricNotAvailable: 'Biometric authentication not available',
    rememberCredentials: 'Remember credentials',
    usePassword: 'Use password',
    // Terms and Conditions
    iAccept: 'I accept the',
    termsAndConditions: 'Terms and Conditions',
    acceptTermsRequired: 'You must accept the Terms and Conditions to register',
    readBible: 'Read Bible',
    quiz: 'Quiz',
    groups: 'Groups',
    onlineNow: 'Online now',
    onlineUsers: 'Online users',
    you: 'You',
    startConversation: 'Start the conversation!',
    writeYourMessage: 'Write your message...',
    unableToSendMessage: 'Unable to send message',
  },
  pt: {
    welcome: 'Bem-vindo',
    goodMorning: 'Bom dia',
    goodAfternoon: 'Boa tarde',
    goodEvening: 'Boa noite',
    dailyVerse: 'Versículo do Dia',
    howAreYou: 'Como você está se sentindo hoje?',
    quickActions: 'Ações Rápidas',
    read: 'Ler',
    write: 'Escrever',
    ask: 'Perguntar',
    theBible: 'A Bíblia',
    inJournal: 'No Diário',
    toAssistant: 'ao Assistente',
    yourProgress: 'Seu Progresso',
    daysInRow: 'Dias seguidos',
    chaptersRead: 'Capítulos lidos',
    journalEntries: 'Entradas no diário',
    community: 'Comunidade',
    translate: 'Traduzir',
    send: 'Enviar',
    login: 'Entrar',
    register: 'Registrar',
    logout: 'Sair',
    settings: 'Configurações',
    language: 'Idioma',
    profile: 'Perfil',
    home: 'Início',
    bible: 'Bíblia',
    journal: 'Diário',
    assistant: 'Assistente',
    donate: 'Doar',
    radios: 'Rádios Evangélicas',
    explore: 'Explorar',
    quizzes: 'Quiz Bíblicos',
    dictionary: 'Dicionário',
    forum: 'Fórum',
    maps: 'Mapas',
    liveEvents: 'Eventos ao Vivo',
    worldwide: 'Mundial',
    error: 'Erro',
    loadError: 'Não foi possível carregar',
    submitError: 'Não foi possível enviar',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    confirm: 'Confirmar',
    yourName: 'Seu nome',
    appLanguage: 'Idioma do app',
    preferredEdition: 'Edição preferida',
    pushNotifications: 'Notificações Push',
    receiveNotifications: 'Receber notificações da comunidade',
    dailyVerseNotification: 'Versículo do Dia',
    receiveVerse: 'Receber um versículo toda manhã',
    info: 'Informações',
    appVersion: 'Versão do app',
    privacyLegal: 'Privacidade e Legal',
    privacyPolicy: 'Política de Privacidade',
    termsOfService: 'Termos de Serviço',
    gdprConsents: 'Gerenciamento de Consentimentos GDPR',
    deleteAccount: 'Excluir Conta',
    logoutAccount: 'Sair da Conta',
    disconnectConfirm: 'Você quer sair da sua conta?',
    deleteConfirm: 'Tem certeza de que deseja excluir sua conta? Esta ação é irreversível.',
    saved: 'Salvo!',
    settingsUpdated: 'Suas configurações foram atualizadas.',
    brother: 'Irmão',
    sister: 'Irmã',
    noQuizzesAvailable: 'Nenhum quiz disponível',
    advancedComingSoon: 'Quiz avançados em breve',
    // Bible screen
    loadingBooks: 'Carregando livros...',
    noBooksAvailable: 'Nenhum livro disponível',
    retry: 'Tentar novamente',
    chapters: 'capítulos',
    editions: 'Edições',
    help: 'Ajuda',
    studyContextAvailable: 'Contexto de estudo disponível',
    yourNotes: 'Suas notas',
    addChapterNote: 'Adicionar nota ao capítulo',
    note: 'Nota',
    aiExplain: 'IA Explica',
    highlight: 'Destacar',
    share: 'Compartilhar',
    bookmark: 'Favorito',
    crossReferences: 'Referências Cruzadas',
    dictionaryTerms: 'Termos do Dicionário',
    historicalContext: 'Contexto Histórico',
    literaryStructure: 'Estrutura Literária',
    keyThemes: 'Temas Principais',
    application: 'Aplicação',
    noteToChapter: 'Nota ao Capítulo',
    writeYourNotes: 'Escreva suas notas...',
    saveNote: 'Salvar Nota',
    aiExplanation: 'Explicação da IA',
    askSpecificQuestion: 'Faça uma pergunta específica (opcional)...',
    askAi: 'Perguntar à IA',
    selectBibleEdition: 'Selecionar Edição Bíblica',
    selectLanguage: 'Selecionar Idioma',
    readingGuide: 'Guia de Leitura',
    changeLanguage: 'Mudar Idioma',
    changeLanguageDesc: 'Toque nas bandeiras acima para mudar o idioma da Bíblia.',
    bibleTranslations: 'Traduções Bíblicas',
    bibleTranslationsDesc: 'O banner acima mostra qual tradução você está lendo.',
    tapVerse: 'Toque em um Versículo',
    tapVerseDesc: 'Toque em qualquer versículo para abrir as ferramentas de estudo.',
    textSize: 'Tamanho do Texto',
    textSizeDesc: 'Toque no botão A para aumentar o tamanho do texto.',
    listen: 'Ouvir',
    listenDesc: 'Toque no ícone do alto-falante para ouvir a leitura do capítulo.',
    understood: 'Entendi!',
    disconnect: 'Desconectar',
    accountDeleted: 'Conta excluída com sucesso',
    deleteAccountError: 'Não foi possível excluir a conta. Tente novamente mais tarde.',
    notifications: 'Notificações',
    email: 'E-mail',
    // Bible screen additional
    verseFromBible: 'Versículo da Bíblia',
    unableToShare: 'Não foi possível compartilhar',
    unableToOpenWikipedia: 'Não foi possível abrir a Wikipedia',
    noteSavedSuccess: 'Nota adicionada com sucesso',
    unableToSaveNote: 'Não foi possível salvar a nota',
    unableToGetExplanation: 'Não foi possível obter a explicação',
    unableToOpenLaParola: 'Não foi possível abrir LaParola',
    theBibleHeader: 'A Bíblia',
    selectEdition: 'Selecionar edição',
    study: 'Estudo',
    wikipedia: 'Wikipedia',
    laParola: 'LaParola',
    personalNotes: 'Adicionar notas pessoais',
    shareWithFriends: 'Compartilhar com amigos',
    saveToBookmarks: 'Salvar nos favoritos',
    explainWithAI: 'Pedir explicação à IA',
    highlightVerse: 'Destacar versículo',
    // Common messages
    noMessagesYet: 'Sem mensagens',
    shareThought: 'Compartilhe um pensamento, uma oração...',
    noPostsYet: 'Ainda não há publicações',
    noGroupsFound: 'Nenhum grupo encontrado',
    notInAnyGroup: 'Você ainda não está em nenhum grupo',
    unableToVote: 'Não foi possível votar',
    fillAllFields: 'Preencha todos os campos',
    unableToCreatePost: 'Não foi possível criar a publicação',
    selectYourMood: 'Selecione seu humor para receber uma palavra personalizada',
    paypalNotAvailable: 'Link do PayPal não disponível',
    enterAmountAndMethod: 'Digite um valor e selecione um método',
    selectAmount: 'Selecionar Valor',
    noResults: 'Nenhum resultado encontrado',
    enterMessage: 'Digite uma mensagem',
    unableToSendMessage: 'Não foi possível enviar a mensagem',
    unableToSubscribe: 'Não foi possível se inscrever',
    unableToCreateEvent: 'Não foi possível criar o evento',
    noEventsScheduled: 'Nenhum evento agendado',
    shareYourHeart: 'Compartilhe seu coração com Deus',
    noFlashcards: 'Sem flashcards',
    noFlashcardsDesc: 'Adicione termos do dicionário para começar a estudar',
    unableToOpenRadio: 'Não foi possível abrir o link da rádio',
    loadingRadios: 'Carregando rádios...',
    noRadiosFound: 'Nenhuma rádio encontrada',
    writeInJournal: 'Escreva algo no diário',
    selectMood: 'Selecione seu humor',
    journalSaved: 'Sua entrada foi salva no diário',
    addToFavorites: 'Adicionar aos Favoritos',
    noFavoritesSaved: 'Nenhum favorito salvo',
    // Community and Forum
    prayer: 'Oração',
    original: 'Original',
    connectWithBrothers: 'Conecte-se com irmãos ao redor do mundo',
    beFirstToShare: 'Seja o primeiro a compartilhar!',
    communityForum: 'Fórum Comunitário',
    all: 'Todos',
    newPost: 'Nova Publicação',
    category: 'Categoria',
    title: 'Título',
    content: 'Conteúdo',
    postTitlePlaceholder: 'Título da publicação...',
    writeYourMessage: 'Escreva sua mensagem...',
    publish: 'Publicar',
    published: 'Publicado!',
    postCreated: 'Sua publicação foi criada',
    beFirstToPost: 'Seja o primeiro a publicar!',
    // Radio
    evangelicalRadios: 'Rádios Evangélicas',
    allRadios: 'Todas as Rádios',
    favorites: 'Favoritos',
    // Continents
    europe: 'Europa',
    southAmerica: 'América do Sul',
    northAmerica: 'América do Norte',
    africa: 'África',
    asia: 'Ásia',
    oceania: 'Oceania',
    // Moods
    moodHappy: 'Feliz',
    moodSad: 'Triste',
    moodAnxious: 'Ansioso',
    moodAngry: 'Com raiva',
    moodGrateful: 'Grato',
    moodConfused: 'Confuso',
    moodHopeful: 'Esperançoso',
    moodTired: 'Cansado',
    // Auth screens
    createAccount: 'Criar Conta',
    startSpiritualJourney: 'Comece sua jornada espiritual',
    fullName: 'Nome completo',
    confirmPassword: 'Confirmar senha',
    alreadyHaveAccount: 'Já tem uma conta?',
    noAccount: 'Não tem uma conta?',
    loginButton: 'Entrar',
    registerButton: 'Registrar',
    orDivider: 'ou',
    continueWithGoogle: 'Continuar com Google',
    dailySpiritualCompanion: 'Seu companheiro espiritual diário',
    fillAllFieldsError: 'Preencha todos os campos',
    passwordMismatchError: 'As senhas não coincidem',
    passwordMinLengthError: 'A senha deve ter pelo menos 6 caracteres',
    enterEmailPassword: 'Digite e-mail e senha',
    registrationFailed: 'Registro falhou',
    loginFailed: 'Login falhou',
    googleSessionNotFound: 'Sessão do Google não encontrada. Tente novamente.',
    googleLoginFailed: 'Login do Google falhou. Verifique sua conexão.',
    // Biometric
    enableBiometric: 'Ativar acesso com impressão digital',
    biometricLogin: 'Entrar com impressão digital',
    biometricPrompt: 'Confirme sua identidade',
    biometricSuccess: 'Autenticação bem-sucedida',
    biometricFailed: 'Autenticação biométrica falhou',
    biometricNotAvailable: 'Autenticação biométrica não disponível',
    rememberCredentials: 'Lembrar credenciais',
    usePassword: 'Usar senha',
    // Terms and Conditions
    iAccept: 'Aceito os',
    termsAndConditions: 'Termos e Condições',
    acceptTermsRequired: 'Você deve aceitar os Termos e Condições para se registrar',
    readBible: 'Ler Bíblia',
    quiz: 'Quiz',
    groups: 'Grupos',
    onlineNow: 'Online agora',
    onlineUsers: 'Usuários online',
  },
  fr: {
    welcome: 'Bienvenue',
    goodMorning: 'Bonjour',
    goodAfternoon: 'Bon après-midi',
    goodEvening: 'Bonsoir',
    dailyVerse: 'Verset du Jour',
    howAreYou: 'Comment vous sentez-vous aujourd\'hui?',
    quickActions: 'Actions Rapides',
    read: 'Lire',
    write: 'Écrire',
    ask: 'Demander',
    theBible: 'La Bible',
    inJournal: 'Dans le Journal',
    toAssistant: "à l'Assistant",
    yourProgress: 'Votre Progrès',
    daysInRow: 'Jours consécutifs',
    chaptersRead: 'Chapitres lus',
    journalEntries: 'Entrées du journal',
    community: 'Communauté',
    translate: 'Traduire',
    send: 'Envoyer',
    login: 'Connexion',
    register: "S'inscrire",
    logout: 'Déconnexion',
    settings: 'Paramètres',
    language: 'Langue',
    profile: 'Profil',
    home: 'Accueil',
    bible: 'Bible',
    journal: 'Journal',
    assistant: 'Assistant',
    donate: 'Donner',
    radios: 'Radios Évangéliques',
    explore: 'Explorer',
    quizzes: 'Quiz Bibliques',
    dictionary: 'Dictionnaire',
    forum: 'Forum',
    maps: 'Cartes',
    liveEvents: 'Événements en Direct',
    worldwide: 'Mondial',
    error: 'Erreur',
    loadError: 'Impossible de charger',
    submitError: 'Impossible d\'envoyer',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    delete: 'Supprimer',
    confirm: 'Confirmer',
    yourName: 'Votre nom',
    appLanguage: 'Langue de l\'app',
    preferredEdition: 'Édition préférée',
    pushNotifications: 'Notifications Push',
    receiveNotifications: 'Recevoir les notifications de la communauté',
    dailyVerseNotification: 'Verset du Jour',
    receiveVerse: 'Recevoir un verset chaque matin',
    info: 'Informations',
    appVersion: 'Version de l\'app',
    privacyLegal: 'Confidentialité et Légal',
    privacyPolicy: 'Politique de Confidentialité',
    termsOfService: 'Conditions d\'Utilisation',
    gdprConsents: 'Gestion des Consentements RGPD',
    deleteAccount: 'Supprimer le Compte',
    logoutAccount: 'Se Déconnecter',
    disconnectConfirm: 'Voulez-vous vous déconnecter de votre compte?',
    deleteConfirm: 'Êtes-vous sûr de vouloir supprimer votre compte? Cette action est irréversible.',
    saved: 'Sauvegardé!',
    settingsUpdated: 'Vos paramètres ont été mis à jour.',
    brother: 'Frère',
    sister: 'Sœur',
    noQuizzesAvailable: 'Aucun quiz disponible',
    advancedComingSoon: 'Quiz avancés bientôt disponibles',
    // Bible screen
    loadingBooks: 'Chargement des livres...',
    noBooksAvailable: 'Aucun livre disponible',
    retry: 'Réessayer',
    chapters: 'chapitres',
    editions: 'Éditions',
    help: 'Aide',
    studyContextAvailable: 'Contexte d\'étude disponible',
    yourNotes: 'Vos notes',
    addChapterNote: 'Ajouter une note au chapitre',
    note: 'Note',
    aiExplain: 'IA Explique',
    highlight: 'Surligner',
    share: 'Partager',
    bookmark: 'Marque-page',
    crossReferences: 'Références Croisées',
    dictionaryTerms: 'Termes du Dictionnaire',
    historicalContext: 'Contexte Historique',
    literaryStructure: 'Structure Littéraire',
    keyThemes: 'Thèmes Clés',
    application: 'Application',
    noteToChapter: 'Note au Chapitre',
    writeYourNotes: 'Écrivez vos notes...',
    saveNote: 'Sauvegarder la Note',
    aiExplanation: 'Explication de l\'IA',
    askSpecificQuestion: 'Posez une question spécifique (optionnel)...',
    askAi: 'Demander à l\'IA',
    selectBibleEdition: 'Sélectionner l\'Édition Biblique',
    selectLanguage: 'Sélectionner la Langue',
    readingGuide: 'Guide de Lecture',
    changeLanguage: 'Changer de Langue',
    changeLanguageDesc: 'Appuyez sur les drapeaux ci-dessus pour changer la langue de la Bible.',
    bibleTranslations: 'Traductions Bibliques',
    bibleTranslationsDesc: 'La bannière ci-dessus montre quelle traduction vous lisez.',
    tapVerse: 'Appuyez sur un Verset',
    tapVerseDesc: 'Appuyez sur n\'importe quel verset pour ouvrir les outils d\'étude.',
    textSize: 'Taille du Texte',
    textSizeDesc: 'Appuyez sur le bouton A pour augmenter la taille du texte.',
    listen: 'Écouter',
    listenDesc: 'Appuyez sur l\'icône du haut-parleur pour écouter la lecture du chapitre.',
    understood: 'Compris!',
    disconnect: 'Déconnecter',
    accountDeleted: 'Compte supprimé avec succès',
    deleteAccountError: 'Impossible de supprimer le compte. Réessayez plus tard.',
    notifications: 'Notifications',
    email: 'E-mail',
    // Bible screen additional
    verseFromBible: 'Verset de la Bible',
    unableToShare: 'Impossible de partager',
    unableToOpenWikipedia: 'Impossible d\'ouvrir Wikipedia',
    noteSavedSuccess: 'Note ajoutée avec succès',
    unableToSaveNote: 'Impossible de sauvegarder la note',
    unableToGetExplanation: 'Impossible d\'obtenir l\'explication',
    unableToOpenLaParola: 'Impossible d\'ouvrir LaParola',
    theBibleHeader: 'La Bible',
    selectEdition: 'Sélectionner l\'édition',
    study: 'Étude',
    wikipedia: 'Wikipédia',
    laParola: 'LaParola',
    personalNotes: 'Ajouter des notes personnelles',
    shareWithFriends: 'Partager avec des amis',
    saveToBookmarks: 'Enregistrer dans les signets',
    explainWithAI: 'Demander une explication à l\'IA',
    highlightVerse: 'Surligner le verset',
    // Common messages
    noMessagesYet: 'Aucun message',
    shareThought: 'Partagez une pensée, une prière...',
    noPostsYet: 'Pas encore de publications',
    noGroupsFound: 'Aucun groupe trouvé',
    notInAnyGroup: 'Vous n\'êtes encore dans aucun groupe',
    unableToVote: 'Impossible de voter',
    fillAllFields: 'Remplissez tous les champs',
    unableToCreatePost: 'Impossible de créer la publication',
    selectYourMood: 'Sélectionnez votre humeur pour recevoir un mot personnalisé',
    paypalNotAvailable: 'Lien PayPal non disponible',
    enterAmountAndMethod: 'Entrez un montant et sélectionnez une méthode',
    selectAmount: 'Sélectionner le Montant',
    noResults: 'Aucun résultat trouvé',
    enterMessage: 'Entrez un message',
    unableToSendMessage: 'Impossible d\'envoyer le message',
    unableToSubscribe: 'Impossible de s\'abonner',
    unableToCreateEvent: 'Impossible de créer l\'événement',
    noEventsScheduled: 'Aucun événement prévu',
    shareYourHeart: 'Partagez votre cœur avec Dieu',
    noFlashcards: 'Pas de flashcards',
    noFlashcardsDesc: 'Ajoutez des termes du dictionnaire pour commencer à étudier',
    unableToOpenRadio: 'Impossible d\'ouvrir le lien de la radio',
    loadingRadios: 'Chargement des radios...',
    noRadiosFound: 'Aucune radio trouvée',
    writeInJournal: 'Écrivez quelque chose dans le journal',
    selectMood: 'Sélectionnez votre humeur',
    journalSaved: 'Votre entrée a été enregistrée dans le journal',
    addToFavorites: 'Ajouter aux Favoris',
    noFavoritesSaved: 'Aucun favori enregistré',
    // Community and Forum
    prayer: 'Prière',
    original: 'Original',
    connectWithBrothers: 'Connectez-vous avec des frères dans le monde',
    beFirstToShare: 'Soyez le premier à partager!',
    communityForum: 'Forum Communautaire',
    all: 'Tous',
    newPost: 'Nouveau Post',
    category: 'Catégorie',
    title: 'Titre',
    content: 'Contenu',
    postTitlePlaceholder: 'Titre du post...',
    writeYourMessage: 'Écrivez votre message...',
    publish: 'Publier',
    published: 'Publié!',
    postCreated: 'Votre post a été créé',
    beFirstToPost: 'Soyez le premier à publier!',
    // Radio
    evangelicalRadios: 'Radios Évangéliques',
    allRadios: 'Toutes les Radios',
    favorites: 'Favoris',
    // Continents
    europe: 'Europe',
    southAmerica: 'Amérique du Sud',
    northAmerica: 'Amérique du Nord',
    africa: 'Afrique',
    asia: 'Asie',
    oceania: 'Océanie',
    // Moods
    moodHappy: 'Heureux',
    moodSad: 'Triste',
    moodAnxious: 'Anxieux',
    moodAngry: 'En colère',
    moodGrateful: 'Reconnaissant',
    moodConfused: 'Confus',
    moodHopeful: 'Plein d\'espoir',
    moodTired: 'Fatigué',
    // Auth screens
    createAccount: 'Créer un Compte',
    startSpiritualJourney: 'Commencez votre voyage spirituel',
    fullName: 'Nom complet',
    confirmPassword: 'Confirmer le mot de passe',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    noAccount: 'Vous n\'avez pas de compte?',
    loginButton: 'Connexion',
    registerButton: 'S\'inscrire',
    orDivider: 'ou',
    continueWithGoogle: 'Continuer avec Google',
    dailySpiritualCompanion: 'Votre compagnon spirituel quotidien',
    fillAllFieldsError: 'Remplissez tous les champs',
    passwordMismatchError: 'Les mots de passe ne correspondent pas',
    passwordMinLengthError: 'Le mot de passe doit contenir au moins 6 caractères',
    enterEmailPassword: 'Entrez e-mail et mot de passe',
    registrationFailed: 'Inscription échouée',
    loginFailed: 'Connexion échouée',
    googleSessionNotFound: 'Session Google non trouvée. Réessayez.',
    googleLoginFailed: 'Connexion Google échouée. Vérifiez votre connexion.',
    // Biometric
    enableBiometric: 'Activer la connexion par empreinte',
    biometricLogin: 'Connexion par empreinte',
    biometricPrompt: 'Confirmez votre identité',
    biometricSuccess: 'Authentification réussie',
    biometricFailed: 'Authentification biométrique échouée',
    biometricNotAvailable: 'Authentification biométrique non disponible',
    rememberCredentials: 'Se souvenir des identifiants',
    usePassword: 'Utiliser le mot de passe',
    // Terms and Conditions
    iAccept: "J'accepte les",
    termsAndConditions: 'Conditions Générales',
    acceptTermsRequired: 'Vous devez accepter les Conditions Générales pour vous inscrire',
    readBible: 'Lire la Bible',
    quiz: 'Quiz',
    groups: 'Groupes',
    onlineNow: 'En ligne maintenant',
    onlineUsers: 'Utilisateurs en ligne',
  },
  de: {
    welcome: 'Willkommen',
    goodMorning: 'Guten Morgen',
    goodAfternoon: 'Guten Tag',
    goodEvening: 'Guten Abend',
    dailyVerse: 'Tagesvers',
    howAreYou: 'Wie fühlst du dich heute?',
    quickActions: 'Schnellaktionen',
    read: 'Lesen',
    write: 'Schreiben',
    ask: 'Fragen',
    theBible: 'Die Bibel',
    inJournal: 'Im Tagebuch',
    toAssistant: 'den Assistenten',
    yourProgress: 'Dein Fortschritt',
    daysInRow: 'Tage in Folge',
    chaptersRead: 'Kapitel gelesen',
    journalEntries: 'Tagebucheinträge',
    community: 'Gemeinschaft',
    translate: 'Übersetzen',
    send: 'Senden',
    login: 'Anmelden',
    register: 'Registrieren',
    logout: 'Abmelden',
    settings: 'Einstellungen',
    language: 'Sprache',
    profile: 'Profil',
    home: 'Start',
    bible: 'Bibel',
    journal: 'Tagebuch',
    assistant: 'Assistent',
    donate: 'Spenden',
    radios: 'Evangelische Radios',
    explore: 'Entdecken',
    quizzes: 'Bibel-Quiz',
    dictionary: 'Wörterbuch',
    forum: 'Forum',
    maps: 'Karten',
    liveEvents: 'Live-Events',
    worldwide: 'Weltweit',
    error: 'Fehler',
    loadError: 'Laden nicht möglich',
    submitError: 'Senden nicht möglich',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    confirm: 'Bestätigen',
    yourName: 'Dein Name',
    appLanguage: 'App-Sprache',
    preferredEdition: 'Bevorzugte Ausgabe',
    pushNotifications: 'Push-Benachrichtigungen',
    receiveNotifications: 'Benachrichtigungen von der Community erhalten',
    dailyVerseNotification: 'Tagesvers',
    receiveVerse: 'Jeden Morgen einen Vers erhalten',
    info: 'Informationen',
    appVersion: 'App-Version',
    privacyLegal: 'Datenschutz & Rechtliches',
    privacyPolicy: 'Datenschutzrichtlinie',
    termsOfService: 'Nutzungsbedingungen',
    gdprConsents: 'DSGVO-Einwilligungsverwaltung',
    deleteAccount: 'Konto Löschen',
    logoutAccount: 'Abmelden',
    disconnectConfirm: 'Möchtest du dich von deinem Konto abmelden?',
    deleteConfirm: 'Bist du sicher, dass du dein Konto löschen möchtest? Diese Aktion ist unwiderruflich.',
    saved: 'Gespeichert!',
    settingsUpdated: 'Deine Einstellungen wurden aktualisiert.',
    brother: 'Bruder',
    sister: 'Schwester',
    noQuizzesAvailable: 'Keine Quiz verfügbar',
    advancedComingSoon: 'Erweiterte Quiz bald verfügbar',
    // Bible screen
    loadingBooks: 'Bücher werden geladen...',
    noBooksAvailable: 'Keine Bücher verfügbar',
    retry: 'Erneut versuchen',
    chapters: 'Kapitel',
    editions: 'Ausgaben',
    help: 'Hilfe',
    studyContextAvailable: 'Studienkontext verfügbar',
    yourNotes: 'Deine Notizen',
    addChapterNote: 'Kapitelnotiz hinzufügen',
    note: 'Notiz',
    aiExplain: 'KI Erklärung',
    highlight: 'Hervorheben',
    share: 'Teilen',
    bookmark: 'Lesezeichen',
    crossReferences: 'Querverweise',
    dictionaryTerms: 'Wörterbuchbegriffe',
    historicalContext: 'Historischer Kontext',
    literaryStructure: 'Literarische Struktur',
    keyThemes: 'Schlüsselthemen',
    application: 'Anwendung',
    noteToChapter: 'Kapitelnotiz',
    writeYourNotes: 'Schreibe deine Notizen...',
    saveNote: 'Notiz Speichern',
    aiExplanation: 'KI-Erklärung',
    askSpecificQuestion: 'Stelle eine spezifische Frage (optional)...',
    askAi: 'KI fragen',
    selectBibleEdition: 'Bibelausgabe Wählen',
    selectLanguage: 'Sprache Wählen',
    readingGuide: 'Leseanleitung',
    changeLanguage: 'Sprache Ändern',
    changeLanguageDesc: 'Tippe auf die Flaggen oben, um die Bibelsprache zu ändern.',
    bibleTranslations: 'Bibelübersetzungen',
    bibleTranslationsDesc: 'Das Banner oben zeigt, welche Übersetzung du liest.',
    tapVerse: 'Tippe auf einen Vers',
    tapVerseDesc: 'Tippe auf einen beliebigen Vers, um die Studienwerkzeuge zu öffnen.',
    textSize: 'Textgröße',
    textSizeDesc: 'Tippe auf den A-Button, um die Textgröße zu erhöhen.',
    listen: 'Anhören',
    listenDesc: 'Tippe auf das Lautsprechersymbol, um das Kapitel vorgelesen zu bekommen.',
    understood: 'Verstanden!',
    disconnect: 'Trennen',
    accountDeleted: 'Konto erfolgreich gelöscht',
    deleteAccountError: 'Konto konnte nicht gelöscht werden. Versuche es später erneut.',
    notifications: 'Benachrichtigungen',
    email: 'E-Mail',
    // Bible screen additional
    verseFromBible: 'Bibelvers',
    unableToShare: 'Teilen nicht möglich',
    unableToOpenWikipedia: 'Wikipedia konnte nicht geöffnet werden',
    noteSavedSuccess: 'Notiz erfolgreich hinzugefügt',
    unableToSaveNote: 'Notiz konnte nicht gespeichert werden',
    unableToGetExplanation: 'Erklärung konnte nicht abgerufen werden',
    unableToOpenLaParola: 'LaParola konnte nicht geöffnet werden',
    theBibleHeader: 'Die Bibel',
    selectEdition: 'Ausgabe wählen',
    study: 'Studium',
    wikipedia: 'Wikipedia',
    laParola: 'LaParola',
    personalNotes: 'Persönliche Notizen hinzufügen',
    shareWithFriends: 'Mit Freunden teilen',
    saveToBookmarks: 'In Lesezeichen speichern',
    explainWithAI: 'KI um Erklärung bitten',
    highlightVerse: 'Vers hervorheben',
    // Common messages
    noMessagesYet: 'Keine Nachrichten',
    shareThought: 'Teile einen Gedanken, ein Gebet...',
    noPostsYet: 'Noch keine Beiträge',
    noGroupsFound: 'Keine Gruppen gefunden',
    notInAnyGroup: 'Du bist noch in keiner Gruppe',
    unableToVote: 'Abstimmen nicht möglich',
    fillAllFields: 'Fülle alle Felder aus',
    unableToCreatePost: 'Beitrag konnte nicht erstellt werden',
    selectYourMood: 'Wähle deine Stimmung, um ein persönliches Wort zu erhalten',
    paypalNotAvailable: 'PayPal-Link nicht verfügbar',
    enterAmountAndMethod: 'Gib einen Betrag ein und wähle eine Methode',
    selectAmount: 'Betrag Wählen',
    noResults: 'Keine Ergebnisse gefunden',
    enterMessage: 'Gib eine Nachricht ein',
    unableToSendMessage: 'Nachricht konnte nicht gesendet werden',
    unableToSubscribe: 'Abonnieren nicht möglich',
    unableToCreateEvent: 'Ereignis konnte nicht erstellt werden',
    noEventsScheduled: 'Keine Ereignisse geplant',
    shareYourHeart: 'Teile dein Herz mit Gott',
    noFlashcards: 'Keine Flashcards',
    noFlashcardsDesc: 'Füge Begriffe aus dem Wörterbuch hinzu, um mit dem Lernen zu beginnen',
    unableToOpenRadio: 'Radio-Link konnte nicht geöffnet werden',
    loadingRadios: 'Radios werden geladen...',
    noRadiosFound: 'Keine Radios gefunden',
    writeInJournal: 'Schreib etwas ins Tagebuch',
    selectMood: 'Wähle deine Stimmung',
    journalSaved: 'Dein Eintrag wurde im Tagebuch gespeichert',
    addToFavorites: 'Zu Favoriten hinzufügen',
    noFavoritesSaved: 'Keine Favoriten gespeichert',
    // Community and Forum
    prayer: 'Gebet',
    original: 'Original',
    connectWithBrothers: 'Verbinde dich mit Brüdern auf der ganzen Welt',
    beFirstToShare: 'Sei der Erste, der teilt!',
    communityForum: 'Gemeinschaftsforum',
    all: 'Alle',
    newPost: 'Neuer Beitrag',
    category: 'Kategorie',
    title: 'Titel',
    content: 'Inhalt',
    postTitlePlaceholder: 'Beitragstitel...',
    writeYourMessage: 'Schreib deine Nachricht...',
    publish: 'Veröffentlichen',
    published: 'Veröffentlicht!',
    postCreated: 'Dein Beitrag wurde erstellt',
    beFirstToPost: 'Sei der Erste, der postet!',
    // Radio
    evangelicalRadios: 'Evangelische Radios',
    allRadios: 'Alle Radios',
    favorites: 'Favoriten',
    // Continents
    europe: 'Europa',
    southAmerica: 'Südamerika',
    northAmerica: 'Nordamerika',
    africa: 'Afrika',
    asia: 'Asien',
    oceania: 'Ozeanien',
    // Moods
    moodHappy: 'Glücklich',
    moodSad: 'Traurig',
    moodAnxious: 'Ängstlich',
    moodAngry: 'Wütend',
    moodGrateful: 'Dankbar',
    moodConfused: 'Verwirrt',
    moodHopeful: 'Hoffnungsvoll',
    moodTired: 'Müde',
    // Auth screens
    createAccount: 'Konto Erstellen',
    startSpiritualJourney: 'Beginne deine spirituelle Reise',
    fullName: 'Vollständiger Name',
    confirmPassword: 'Passwort bestätigen',
    alreadyHaveAccount: 'Hast du bereits ein Konto?',
    noAccount: 'Hast du kein Konto?',
    loginButton: 'Anmelden',
    registerButton: 'Registrieren',
    orDivider: 'oder',
    continueWithGoogle: 'Mit Google fortfahren',
    dailySpiritualCompanion: 'Dein täglicher spiritueller Begleiter',
    fillAllFieldsError: 'Fülle alle Felder aus',
    passwordMismatchError: 'Passwörter stimmen nicht überein',
    passwordMinLengthError: 'Passwort muss mindestens 6 Zeichen haben',
    enterEmailPassword: 'Gib E-Mail und Passwort ein',
    registrationFailed: 'Registrierung fehlgeschlagen',
    loginFailed: 'Anmeldung fehlgeschlagen',
    googleSessionNotFound: 'Google-Sitzung nicht gefunden. Versuche es erneut.',
    googleLoginFailed: 'Google-Anmeldung fehlgeschlagen. Überprüfe deine Verbindung.',
    // Biometric
    enableBiometric: 'Fingerabdruck-Login aktivieren',
    biometricLogin: 'Mit Fingerabdruck anmelden',
    biometricPrompt: 'Bestätige deine Identität',
    biometricSuccess: 'Authentifizierung erfolgreich',
    biometricFailed: 'Biometrische Authentifizierung fehlgeschlagen',
    biometricNotAvailable: 'Biometrische Authentifizierung nicht verfügbar',
    rememberCredentials: 'Anmeldedaten merken',
    usePassword: 'Passwort verwenden',
    // Terms and Conditions
    iAccept: 'Ich akzeptiere die',
    termsAndConditions: 'Allgemeinen Geschäftsbedingungen',
    acceptTermsRequired: 'Du musst die AGB akzeptieren, um dich zu registrieren',
    readBible: 'Bibel lesen',
    quiz: 'Quiz',
    groups: 'Gruppen',
    onlineNow: 'Jetzt online',
    onlineUsers: 'Online-Benutzer',
  },
};

export const useTranslation = () => {
  const { currentLanguage } = useLanguageStore();
  
  const t = (key: string): string => {
    return translations[currentLanguage]?.[key] || translations['it'][key] || key;
  };
  
  return { t, currentLanguage };
};
