import { create } from 'zustand';
import AsyncStorage from '@react-native-async-storage/async-storage';

interface Language {
  name: string;
  flag: string;
  tts_code: string;
}

interface LanguageState {
  currentLanguage: string;
  languages: Record<string, Language>;
  setLanguage: (lang: string) => Promise<void>;
  loadLanguage: () => Promise<void>;
  loadLanguages: () => Promise<void>;
}

const API_URL = process.env.EXPO_PUBLIC_BACKEND_URL || '';

export const useLanguageStore = create<LanguageState>((set, get) => ({
  currentLanguage: 'it',
  languages: {
    it: { name: 'Italiano', flag: '🇮🇹', tts_code: 'it-IT' },
    es: { name: 'Español', flag: '🇪🇸', tts_code: 'es-ES' },
    en: { name: 'English', flag: '🇬🇧', tts_code: 'en-US' },
    pt: { name: 'Português', flag: '🇧🇷', tts_code: 'pt-BR' },
    fr: { name: 'Français', flag: '🇫🇷', tts_code: 'fr-FR' },
    de: { name: 'Deutsch', flag: '🇩🇪', tts_code: 'de-DE' },
  },

  setLanguage: async (lang: string) => {
    await AsyncStorage.setItem('app_language', lang);
    set({ currentLanguage: lang });
  },

  loadLanguage: async () => {
    const saved = await AsyncStorage.getItem('app_language');
    if (saved) {
      set({ currentLanguage: saved });
    }
  },

  loadLanguages: async () => {
    try {
      const response = await fetch(`${API_URL}/api/languages`);
      if (response.ok) {
        const data = await response.json();
        set({ languages: data });
      }
    } catch (error) {
      console.log('Error loading languages:', error);
    }
  },
}));

// UI Translations
export const translations: Record<string, Record<string, string>> = {
  it: {
    welcome: 'Benvenuto',
    goodMorning: 'Buongiorno',
    goodAfternoon: 'Buon pomeriggio',
    goodEvening: 'Buonasera',
    dailyVerse: 'Versetto del Giorno',
    howAreYou: 'Come ti senti oggi?',
    quickActions: 'Azioni Rapide',
    read: 'Leggi',
    write: 'Scrivi',
    ask: 'Chiedi',
    theBible: 'La Bibbia',
    inJournal: 'Nel Diario',
    toAssistant: "All'Assistente",
    yourProgress: 'Il Tuo Progresso',
    daysInRow: 'Giorni di fila',
    chaptersRead: 'Capitoli letti',
    journalEntries: 'Voci diario',
    community: 'Community',
    translate: 'Traduci',
    send: 'Invia',
    login: 'Accedi',
    register: 'Registrati',
    logout: 'Esci',
    settings: 'Impostazioni',
    language: 'Lingua',
    profile: 'Profilo',
    home: 'Home',
    bible: 'Bibbia',
    journal: 'Diario',
    assistant: 'Assistente',
    donate: 'Dona',
    radios: 'Radio Evangeliche',
    explore: 'Esplora',
    quizzes: 'Quiz Biblici',
    dictionary: 'Dizionario',
    forum: 'Forum',
    maps: 'Mappe',
    liveEvents: 'Eventi Live',
    worldwide: 'Mondiale',
    error: 'Errore',
    loadError: 'Impossibile caricare',
    submitError: 'Impossibile inviare',
    save: 'Salva',
    cancel: 'Annulla',
    delete: 'Elimina',
    confirm: 'Conferma',
    yourName: 'Il tuo nome',
    appLanguage: 'Lingua dell\'app',
    preferredEdition: 'Edizione preferita',
    pushNotifications: 'Notifiche Push',
    receiveNotifications: 'Ricevi notifiche dalla community',
    dailyVerseNotification: 'Versetto del Giorno',
    receiveVerse: 'Ricevi un versetto ogni mattina',
    info: 'Informazioni',
    appVersion: 'Versione app',
    privacyLegal: 'Privacy e Legale',
    privacyPolicy: 'Informativa sulla Privacy',
    termsOfService: 'Termini di Servizio',
    gdprConsents: 'Gestione Consensi GDPR',
    deleteAccount: 'Elimina Account',
    logoutAccount: 'Esci dall\'Account',
    disconnectConfirm: 'Vuoi uscire dal tuo account?',
    deleteConfirm: 'Sei sicuro di voler eliminare il tuo account? Questa azione è irreversibile.',
    saved: 'Salvato!',
    settingsUpdated: 'Le tue impostazioni sono state aggiornate.',
    brother: 'Fratello',
    sister: 'Sorella',
    noQuizzesAvailable: 'Nessun quiz disponibile',
    advancedComingSoon: 'Quiz avanzati disponibili prossimamente',
  },
  es: {
    welcome: 'Bienvenido',
    goodMorning: 'Buenos días',
    goodAfternoon: 'Buenas tardes',
    goodEvening: 'Buenas noches',
    dailyVerse: 'Versículo del Día',
    howAreYou: '¿Cómo te sientes hoy?',
    quickActions: 'Acciones Rápidas',
    read: 'Leer',
    write: 'Escribir',
    ask: 'Preguntar',
    theBible: 'La Biblia',
    inJournal: 'En el Diario',
    toAssistant: 'Al Asistente',
    yourProgress: 'Tu Progreso',
    daysInRow: 'Días seguidos',
    chaptersRead: 'Capítulos leídos',
    journalEntries: 'Entradas del diario',
    community: 'Comunidad',
    translate: 'Traducir',
    send: 'Enviar',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    logout: 'Salir',
    settings: 'Configuración',
    language: 'Idioma',
    profile: 'Perfil',
    home: 'Inicio',
    bible: 'Biblia',
    journal: 'Diario',
    assistant: 'Asistente',
    donate: 'Donar',
    radios: 'Radios Evangélicas',
    explore: 'Explorar',
    quizzes: 'Quiz Bíblicos',
    dictionary: 'Diccionario',
    forum: 'Foro',
    maps: 'Mapas',
    liveEvents: 'Eventos en Vivo',
    worldwide: 'Mundial',
    error: 'Error',
    loadError: 'No se puede cargar',
    submitError: 'No se puede enviar',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    confirm: 'Confirmar',
    yourName: 'Tu nombre',
    appLanguage: 'Idioma de la app',
    preferredEdition: 'Edición preferida',
    pushNotifications: 'Notificaciones Push',
    receiveNotifications: 'Recibir notificaciones de la comunidad',
    dailyVerseNotification: 'Versículo del Día',
    receiveVerse: 'Recibir un versículo cada mañana',
    info: 'Información',
    appVersion: 'Versión de la app',
    privacyLegal: 'Privacidad y Legal',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    gdprConsents: 'Gestión de Consentimientos GDPR',
    deleteAccount: 'Eliminar Cuenta',
    logoutAccount: 'Cerrar Sesión',
    disconnectConfirm: '¿Quieres salir de tu cuenta?',
    deleteConfirm: '¿Estás seguro de que deseas eliminar tu cuenta? Esta acción es irreversible.',
    saved: '¡Guardado!',
    settingsUpdated: 'Tu configuración ha sido actualizada.',
    brother: 'Hermano',
    sister: 'Hermana',
    noQuizzesAvailable: 'No hay quiz disponibles',
    advancedComingSoon: 'Quiz avanzados disponibles próximamente',
  },
  en: {
    welcome: 'Welcome',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    dailyVerse: 'Daily Verse',
    howAreYou: 'How are you feeling today?',
    quickActions: 'Quick Actions',
    read: 'Read',
    write: 'Write',
    ask: 'Ask',
    theBible: 'The Bible',
    inJournal: 'In Journal',
    toAssistant: 'the Assistant',
    yourProgress: 'Your Progress',
    daysInRow: 'Days in a row',
    chaptersRead: 'Chapters read',
    journalEntries: 'Journal entries',
    community: 'Community',
    translate: 'Translate',
    send: 'Send',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    settings: 'Settings',
    language: 'Language',
    profile: 'Profile',
    home: 'Home',
    bible: 'Bible',
    journal: 'Journal',
    assistant: 'Assistant',
    donate: 'Donate',
    radios: 'Evangelical Radios',
    explore: 'Explore',
    quizzes: 'Bible Quizzes',
    dictionary: 'Dictionary',
    forum: 'Forum',
    maps: 'Maps',
    liveEvents: 'Live Events',
    worldwide: 'Worldwide',
    error: 'Error',
    loadError: 'Unable to load',
    submitError: 'Unable to submit',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    yourName: 'Your name',
    appLanguage: 'App language',
    preferredEdition: 'Preferred edition',
    pushNotifications: 'Push Notifications',
    receiveNotifications: 'Receive notifications from the community',
    dailyVerseNotification: 'Daily Verse',
    receiveVerse: 'Receive a verse every morning',
    info: 'Information',
    appVersion: 'App version',
    privacyLegal: 'Privacy & Legal',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    gdprConsents: 'GDPR Consent Management',
    deleteAccount: 'Delete Account',
    logoutAccount: 'Logout',
    disconnectConfirm: 'Do you want to log out of your account?',
    deleteConfirm: 'Are you sure you want to delete your account? This action is irreversible.',
    saved: 'Saved!',
    settingsUpdated: 'Your settings have been updated.',
    brother: 'Brother',
    sister: 'Sister',
    noQuizzesAvailable: 'No quizzes available',
    advancedComingSoon: 'Advanced quizzes coming soon',
  },
  pt: {
    welcome: 'Bem-vindo',
    goodMorning: 'Bom dia',
    goodAfternoon: 'Boa tarde',
    goodEvening: 'Boa noite',
    dailyVerse: 'Versículo do Dia',
    howAreYou: 'Como você está se sentindo hoje?',
    quickActions: 'Ações Rápidas',
    read: 'Ler',
    write: 'Escrever',
    ask: 'Perguntar',
    theBible: 'A Bíblia',
    inJournal: 'No Diário',
    toAssistant: 'ao Assistente',
    yourProgress: 'Seu Progresso',
    daysInRow: 'Dias seguidos',
    chaptersRead: 'Capítulos lidos',
    journalEntries: 'Entradas no diário',
    community: 'Comunidade',
    translate: 'Traduzir',
    send: 'Enviar',
    login: 'Entrar',
    register: 'Registrar',
    logout: 'Sair',
    settings: 'Configurações',
    language: 'Idioma',
    profile: 'Perfil',
    home: 'Início',
    bible: 'Bíblia',
    journal: 'Diário',
    assistant: 'Assistente',
    donate: 'Doar',
    radios: 'Rádios Evangélicas',
    explore: 'Explorar',
    quizzes: 'Quiz Bíblicos',
    dictionary: 'Dicionário',
    forum: 'Fórum',
    maps: 'Mapas',
    liveEvents: 'Eventos ao Vivo',
    worldwide: 'Mundial',
    error: 'Erro',
    loadError: 'Não foi possível carregar',
    submitError: 'Não foi possível enviar',
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    confirm: 'Confirmar',
    yourName: 'Seu nome',
    appLanguage: 'Idioma do app',
    preferredEdition: 'Edição preferida',
    pushNotifications: 'Notificações Push',
    receiveNotifications: 'Receber notificações da comunidade',
    dailyVerseNotification: 'Versículo do Dia',
    receiveVerse: 'Receber um versículo toda manhã',
    info: 'Informações',
    appVersion: 'Versão do app',
    privacyLegal: 'Privacidade e Legal',
    privacyPolicy: 'Política de Privacidade',
    termsOfService: 'Termos de Serviço',
    gdprConsents: 'Gerenciamento de Consentimentos GDPR',
    deleteAccount: 'Excluir Conta',
    logoutAccount: 'Sair da Conta',
    disconnectConfirm: 'Você quer sair da sua conta?',
    deleteConfirm: 'Tem certeza de que deseja excluir sua conta? Esta ação é irreversível.',
    saved: 'Salvo!',
    settingsUpdated: 'Suas configurações foram atualizadas.',
    brother: 'Irmão',
    sister: 'Irmã',
    noQuizzesAvailable: 'Nenhum quiz disponível',
    advancedComingSoon: 'Quiz avançados em breve',
  },
  fr: {
    welcome: 'Bienvenue',
    goodMorning: 'Bonjour',
    goodAfternoon: 'Bon après-midi',
    goodEvening: 'Bonsoir',
    dailyVerse: 'Verset du Jour',
    howAreYou: 'Comment vous sentez-vous aujourd\'hui?',
    quickActions: 'Actions Rapides',
    read: 'Lire',
    write: 'Écrire',
    ask: 'Demander',
    theBible: 'La Bible',
    inJournal: 'Dans le Journal',
    toAssistant: "à l'Assistant",
    yourProgress: 'Votre Progrès',
    daysInRow: 'Jours consécutifs',
    chaptersRead: 'Chapitres lus',
    journalEntries: 'Entrées du journal',
    community: 'Communauté',
    translate: 'Traduire',
    send: 'Envoyer',
    login: 'Connexion',
    register: "S'inscrire",
    logout: 'Déconnexion',
    settings: 'Paramètres',
    language: 'Langue',
    profile: 'Profil',
    home: 'Accueil',
    bible: 'Bible',
    journal: 'Journal',
    assistant: 'Assistant',
    donate: 'Donner',
    radios: 'Radios Évangéliques',
    explore: 'Explorer',
    quizzes: 'Quiz Bibliques',
    dictionary: 'Dictionnaire',
    forum: 'Forum',
    maps: 'Cartes',
    liveEvents: 'Événements en Direct',
    worldwide: 'Mondial',
    error: 'Erreur',
    loadError: 'Impossible de charger',
    submitError: 'Impossible d\'envoyer',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    delete: 'Supprimer',
    confirm: 'Confirmer',
    yourName: 'Votre nom',
    appLanguage: 'Langue de l\'app',
    preferredEdition: 'Édition préférée',
    pushNotifications: 'Notifications Push',
    receiveNotifications: 'Recevoir les notifications de la communauté',
    dailyVerseNotification: 'Verset du Jour',
    receiveVerse: 'Recevoir un verset chaque matin',
    info: 'Informations',
    appVersion: 'Version de l\'app',
    privacyLegal: 'Confidentialité et Légal',
    privacyPolicy: 'Politique de Confidentialité',
    termsOfService: 'Conditions d\'Utilisation',
    gdprConsents: 'Gestion des Consentements RGPD',
    deleteAccount: 'Supprimer le Compte',
    logoutAccount: 'Se Déconnecter',
    disconnectConfirm: 'Voulez-vous vous déconnecter de votre compte?',
    deleteConfirm: 'Êtes-vous sûr de vouloir supprimer votre compte? Cette action est irréversible.',
    saved: 'Sauvegardé!',
    settingsUpdated: 'Vos paramètres ont été mis à jour.',
    brother: 'Frère',
    sister: 'Sœur',
    noQuizzesAvailable: 'Aucun quiz disponible',
    advancedComingSoon: 'Quiz avancés bientôt disponibles',
  },
  de: {
    welcome: 'Willkommen',
    goodMorning: 'Guten Morgen',
    goodAfternoon: 'Guten Tag',
    goodEvening: 'Guten Abend',
    dailyVerse: 'Tagesvers',
    howAreYou: 'Wie fühlst du dich heute?',
    quickActions: 'Schnellaktionen',
    read: 'Lesen',
    write: 'Schreiben',
    ask: 'Fragen',
    theBible: 'Die Bibel',
    inJournal: 'Im Tagebuch',
    toAssistant: 'den Assistenten',
    yourProgress: 'Dein Fortschritt',
    daysInRow: 'Tage in Folge',
    chaptersRead: 'Kapitel gelesen',
    journalEntries: 'Tagebucheinträge',
    community: 'Gemeinschaft',
    translate: 'Übersetzen',
    send: 'Senden',
    login: 'Anmelden',
    register: 'Registrieren',
    logout: 'Abmelden',
    settings: 'Einstellungen',
    language: 'Sprache',
    profile: 'Profil',
    home: 'Start',
    bible: 'Bibel',
    journal: 'Tagebuch',
    assistant: 'Assistent',
    donate: 'Spenden',
    radios: 'Evangelische Radios',
    explore: 'Entdecken',
    quizzes: 'Bibel-Quiz',
    dictionary: 'Wörterbuch',
    forum: 'Forum',
    maps: 'Karten',
    liveEvents: 'Live-Events',
    worldwide: 'Weltweit',
    error: 'Fehler',
    loadError: 'Laden nicht möglich',
    submitError: 'Senden nicht möglich',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    confirm: 'Bestätigen',
    yourName: 'Dein Name',
    appLanguage: 'App-Sprache',
    preferredEdition: 'Bevorzugte Ausgabe',
    pushNotifications: 'Push-Benachrichtigungen',
    receiveNotifications: 'Benachrichtigungen von der Community erhalten',
    dailyVerseNotification: 'Tagesvers',
    receiveVerse: 'Jeden Morgen einen Vers erhalten',
    info: 'Informationen',
    appVersion: 'App-Version',
    privacyLegal: 'Datenschutz & Rechtliches',
    privacyPolicy: 'Datenschutzrichtlinie',
    termsOfService: 'Nutzungsbedingungen',
    gdprConsents: 'DSGVO-Einwilligungsverwaltung',
    deleteAccount: 'Konto Löschen',
    logoutAccount: 'Abmelden',
    disconnectConfirm: 'Möchtest du dich von deinem Konto abmelden?',
    deleteConfirm: 'Bist du sicher, dass du dein Konto löschen möchtest? Diese Aktion ist unwiderruflich.',
    saved: 'Gespeichert!',
    settingsUpdated: 'Deine Einstellungen wurden aktualisiert.',
    brother: 'Bruder',
    sister: 'Schwester',
    noQuizzesAvailable: 'Keine Quiz verfügbar',
    advancedComingSoon: 'Erweiterte Quiz bald verfügbar',
  },
};

export const useTranslation = () => {
  const { currentLanguage } = useLanguageStore();
  
  const t = (key: string): string => {
    return translations[currentLanguage]?.[key] || translations['it'][key] || key;
  };
  
  return { t, currentLanguage };
};
